### ISSUE TITLE
[Bug?]: Return Key doesn´t work... 

### ISSUE THREAD

**Issue by Kimet1970** [emoose/OutRun2006Tweaks#104]
### Tweaks version

Using Tweaks 0.4.2...
Is it a game bug? Or a question related my wirelles modern keyboard?
My return key doesn't work in the game!
(But it works on my Samsung Book 2 notebook...)
And the Space key works as the Return...
But no on every menu!

**Comment by emoose** [comment]
Does the enter key work with vanilla game (with dinput8.dll removed)?

It could be worth trying with `ControllerHotPlug = false` in INI, seems that had issues with input for lots of other people.

**Comment by Left-Empty** [comment]
I have had this issue at random in parts of the interface, as well as other keys (such as Escape), and ControllerHotPlug never fixed it. This happens in the base game as well. Also tied, control reconfiguration is totally messed up, and even if the default control scheme works on the Xbox pad (the only control I can use, even the keyboard doesn't work), the control config menu shows most of its buttons are assigned to keyboard keys :D 

Sadly, this issue prevents me from logging onto the multiplayer: at account creation, while I can enter a password and confirm it with both keyboard and gamepad, I can't do the same for a username: pressing "Done" or pressing enter does nothing, and Escape aborts the whole process.
Cheers, awesome to play the game again!

**Comment by Left-Empty** [comment]
Fixed here by simply turning off hotplug, which I had done once and somehow had turn back on. Fixes all my issues here.

**Comment by Kimet1970** [comment]
> Fixed here by simply turning off hotplug, which I had done once and somehow had turn back on. Fixes all my issues here.

Solved to me!!!
Many thanks!!!
