### ISSUE TITLE
[Feature Request]: Play with the alternative drivers

### ISSUE THREAD

**Issue by envido32** [emoose/OutRun2006Tweaks#110]
There are models, textures and even a hidden selection screen when editing the license that let's play with other drivers. 
They can be easily be used by doing a simple edit to the Save File. The animations have some issues (specially when selecting the girls as drivers) but apart from that I didn't had mayor problems.

https://tcrf.net/OutRun_2006:_Coast_2_Coast_(Windows)#Driver_Selection_Screen

**Comment by lance8765** [comment]
Duplicate of #78.
