### ISSUE TITLE
[Bug]: user.ini file not being applied

### ISSUE THREAD

**Issue by k0pp0** [emoose/OutRun2006Tweaks#118]
### Tweaks version

OutRun2006Tweaks-0.5.1b.zip

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

[OutRun2006TweakslogAndIni.zip](https://github.com/user-attachments/files/16688649/OutRun2006TweakslogAndIni.zip)
Have a few settings in my user.ini that I want to keep (reduced reflections etc) due to having a n100 to run this on.

Using the latest version doesn't take across those settings 😭

**Comment by emoose** [comment]
Ah you might need to add the sections for the ini too, eg. most of those in the user.ini you posted should be under [Graphics] iirc, that seems to let it work for me.

**Comment by equinoxe3d** [comment]
Same issue, but adding the sections of the settings I tweaked solved it for me

**Comment by k0pp0** [comment]
AHH yeah that makes sense!! Will try and report back

**Comment by k0pp0** [comment]
Sorry forgot to close this, suggested fixes worked
