### ISSUE TITLE
[Feature Request]: Hi-res driver models/textures (obj_chr_dr_?h??_pmt)

### ISSUE THREAD

**Issue by Tenome** [emoose/OutRun2006Tweaks#135]
### Describe the feature you'd like to see added

According to Howard's note on the file archives, 

- `gal/g00`=clarissa 
- `gal_usa/g00_usa`=censored clarissa
- `h00`=holly
- `fal/l00`=jennifer
- `mal/m00`=alberto
- `s00=sam` (blonde male)
- `w00=wolf` (black haired male)

`obj_chr_dr_???_pmt` - driver model and textures (use notes above)
`obj_chr_dr_?h??_pmt` - hi res driver model and textures 
`obj_chr_???_pmt` - models used in endings (unlike the driver versions these have legs and bigger textures)
`obj_chr_aut??_pmt` - alternate costumes for the drivers?? used by rivals maybe??

Does the game ever load a high-res driver? At the very least, the texture dump hasn't caught it yet. The normal driver models are kinda janky, but is there a higher quality model that remains unused by the game that could be loaded instead? It doesn't look like any of the available OR2 tools support ripping from the pmt archives either, so I can't check that way.

**Comment by emoose** [comment]
Does switching the files make any difference?

I'm not really sure if the ?h?? files are actually hi-res though, seems the game internally splits the two car models into driver & heroine, maybe the h just means it's heroine/passenger.

**Comment by Tenome** [comment]
I forgot obj_chr_aut??_pmt, which also has driver skins apparently but isn't extracted. 

Swapping the files does load what looks like an HD face for Alberto (albeit really creepy, eternally staring into the void), but the rest of his model is broken. I tried dumping with this swap enabled, but I'm not sure if I see this face texture in the dump folder.

![OR2006C2C_1725993822f24618dc-c71a-41d6-95ec-e6091ce2aae1](https://github.com/user-attachments/assets/812751fc-51a5-4579-8340-362e1736a816)
![OR2006C2C_17259919483b8c4c57-d281-419a-bf9f-95df7f4fc674](https://github.com/user-attachments/assets/347b636a-6bec-4259-98b4-71d8237b6708)

**Comment by emoose** [comment]
Oh neat, looks like 6549B0 (4 bytes) -> 0xC might let it load in, don't have camera setup to see it close though, could you check if that works?

**Comment by emoose** [comment]
Seems it works, Clarissa also has a hi-def model that can load in too:
![OR2006C2C_2024-09-10_23-48-03](https://github.com/user-attachments/assets/55215d7c-837f-4e5c-8898-4f03a8e14168)
->
![OR2006C2C_2024-09-10_23-47-26](https://github.com/user-attachments/assets/787d1489-984d-4680-988f-a81e48290c36)

For Clarissa change 6549D8 (4 bytes) -> 7, not sure if the other girls have hi-def versions though, seems only LH00 / MH00 are left which iirc are unused clarissa variants?

**Comment by Tenome** [comment]
Aha, I knew it! Thanks. But those aren't the cutscene archives, are they? Alberto doesn't look like that in the endings.

**Comment by Tenome** [comment]
That was fast, thanks!

**Comment by emoose** [comment]
The cutscene models are different again, anims are pretty busted if you force those to load, guess the modelled legs would probably cause issues too.

OCP\Driver\ is interesting, doesn't seem game tries to read from there but does load from Driver\ folder, which has mostly same filenames inside, guess OCP\Driver\ could just be a leftover (maybe they accidentally copied Drivers folder into OCP at some point)

**Comment by Tenome** [comment]
Damn! Guess I'll leave it off for now.

**Comment by emoose** [comment]
Oh I meant if you forced the cutscene models to load in as the driver they would be busted, the cutscenes themselves shouldn't be affected by this afaik, just driver models, haven't seen anything actually broken with this yet on my end.

**Comment by Tenome** [comment]
He pinged you, but I'm reposting here just in case (and for posterity).

![Discord_1726101155790b7772-1f90-4bd4-9a9b-c45dceb4107e](https://github.com/user-attachments/assets/72c07e04-154a-4efc-9169-316248cd566e)

**Comment by emoose** [comment]
Haven't been able to reproduce that on my side, Clarissa seems fine for me in each mode I tried, @ChibiDreamweaver could you post the INI you used which had that?

**Comment by Dekaid0011** [comment]
> Haven't been able to reproduce that on my side, Clarissa seems fine for me in each mode I tried, @ChibiDreamweaver could you post the INI you used which had that? Also which menu options did you pick to load in?

To reproduce this bug you have to finish a Heart Attack Mode run in 2SP where the ending cutscenes play. If you start another HA run afterwards you get the glitched hair, both in 2SP mode and in Single Player mode.

**Comment by emoose** [comment]
@Dekaid0011 ahh thanks for the info, was able to get it happening on my side.

Took some digging but think I got the cause, some data for hair movement was leftover after ending cutscene ended, driver/passenger models wouldn't update that data but seems HQ models would still try to read from it, so ended up using stale data from the cutscene...

Just updated it so that data is cleared when character is being setup, seems to fix it on my end.

**Comment by ChibiDreamweaver** [comment]
> @Dekaid0011 ahh thanks for the info, was able to get it happening on my side.
> 
> Took some digging but think I got the cause, some data for hair movement was leftover after ending cutscene ended, driver/passenger models wouldn't update that data but seems HQ models would still try to read from it, so ended up using stale data from the cutscene...
> 
> Just updated it so that data is cleared when character is being setup, seems to fix it on my end, build at https://github.com/emoose/OutRun2006Tweaks/actions/runs/10861576522
> 
> (now I wonder, if HQ models are setup to use hair movement, could it be enabled for ingame too? I noticed hair was pretty static when driving...)

![9917044177571414016_14](https://github.com/user-attachments/assets/bf7a4e07-b3dc-4d03-a908-22d0b0aec8ba)

Clarissa is now no longer Johnny Bravo but is missing her ponytail. not sure what is causing this specific issue. it seems like it is not created by ending cutscenes as caused by the previous issue but the missing ponytail issue is caused right when Heart Attack mode is started. I see that this affects both Coast 2 Coast and OutRun 2SP modes. I just thought I let you know about this.

**Comment by emoose** [comment]
>Clarissa is now no longer Johnny Bravo but is missing her ponytail. 

Oh good eye, looks like the hi-def anim file is missing the anim for hair completely, guess this could have been main cause for the johnny bravo issue too.

Might have found a easy fix for it though: copy `Media\CHR_DR_GH00.bin` & `Media\CHR_DR_GH00_USA.bin` into the Chr\ folder, overwriting the files that are there - looks like the ones in Media\ do contain the hair anim, but game just doesn't use them for some reason.

Not sure if this could cause any other issues though, but seems to fix ponytail at least.
Can probably get tweaks to make the game use these files instead automatically, but would appreciate anyone testing it first to make sure nothing else breaks with it.

(Media folder does have anims for other models there too which the game never tries to use - wonder if these could all be updated versions which were accidentally left unused, just like how lens_flare_offset.bin was left unused in the same folder...)

**Comment by Tenome** [comment]
Just don't copy-paste all of them like I did, or else Clarissa will suddenly start speaking barely-audible Japanese lol.

**Comment by ChibiDreamweaver** [comment]
> > Clarissa is now no longer Johnny Bravo but is missing her ponytail.
> 
> Oh good eye, looks like the hi-def anim file is missing the anim for hair completely, guess this could have been main cause for the johnny bravo issue too.
> 
> Might have found a easy fix for it though: copy `Media\CHR_DR_GH00.bin` & `Media\CHR_DR_GH00_USA.bin` into the `Chr\` folder, overwriting the files that are there - looks like these `Media\` ones do contain the hair anim, but game just doesn't use them for some reason. Not sure if this could cause any other issues though, but seems to fix ponytail at least, would appreciate anyone testing it to make sure nothing else breaks with it.
> 
> Maybe can get tweaks to get the game to load these Media files instead of the Chr ones, will look into it soon.
> 
> (Media folder does have anims for other models there too which the game never tries to use - wonder if these could all be updated versions which were accidentally left unused, just like how lens_flare_offset.bin was left unused in the same folder...)

I'll get to finding the files you listed right now. will let you know if I spot more issues

**Comment by ChibiDreamweaver** [comment]
![ClarissaPonytail](https://github.com/user-attachments/assets/5da0d109-9b33-4ed2-990f-eddbb4fd58cf)
The HQ models may be hard to see in this screenshot but her ponytail is back!

**Comment by emoose** [comment]
Weird thing with the media folder, looks like besides the ghost .rec files only like 2 files inside it are actually loaded by the game, the rest of the files there are things meant to be loaded from other folders.

Maybe whatever build process created these files would always just write them into Media, and then it was up to the devs to move them out manually - or it could be the opposite, maybe an older build process wrote them into Media\ and then later they changed things to use other dirs instead, but left some things in Media by mistake (in original OR2 Xbox & arcade all the files were pretty much in a single folder...)

Wonder if any release might have left file timestamps intact, maybe one of the ISOs, hm...

**Comment by emoose** [comment]
https://github.com/emoose/OutRun2006Tweaks/commit/e2802418638d6b6492937c9882aeb37f50d524b8 should let it load the Media version automatically, no need to copy files around (if you already copied you can revert it if you like, or just leave it)

Build at https://github.com/emoose/OutRun2006Tweaks/actions/runs/10886997836

**Comment by DonelBueno** [comment]
Are HQ Characters safe now? what about the "AllowCharacterSelection" option?

**Comment by emoose** [comment]
Haven't seen any other issues with HQ chars myself, but then again I did miss the hair issues :P
If no other issues are found I'll probably make a release with it soon.

AllowCharSelection still has issues with the female chars, tried switching some data in the EXE but haven't had any luck fixing them, wonder if switching the bin files could change anything.
(if not maybe can look into removing the female options, the male chars seem to mostly work fine besides some model issues)

**Comment by thegreatprophetzarquon** [comment]
First off, this is so very cool. Second, for those, like me, who were curious what exactly the "HiDef" models are, it looks like they are used in-game in both the Lindbergh and original [Chihiro](https://youtu.be/-hj9w4NXYI8?t=172) versions of the game, and they first made lower-detailed versions for the Xbox port for performance. (which makes sense as you only see the back of their heads for most of a race).
This was never reverted for the [OutRun Online Arcade](https://youtu.be/8Yi5xXZii5I?t=22) port, which means this is now the first home version that uses the original models!

**Comment by emoose** [comment]
@thegreatprophetzarquon oh interesting, didn't realize arcade and console ports were even using different models lol.

Hoping that'll mean the HD ones should have most anims working fine then, not sure if they ever added any custom ones for C2C specifically, haven't heard of anything being broken yet at least.

Since it seems to be working fine I guess we can close it, thanks again @Tenome for bringing them up!
