### ISSUE TITLE
[Feature Request]: Adding in female announcer and ending sequences.

### ISSUE THREAD

**Issue by BlockABoots** [emoose/OutRun2006Tweaks#137]
### Describe the feature you'd like to see added

Have noticed that the PC version seems to be missing the female voice announcer say the model name of the car you select on the car select screen and also the name of the music track selected. Also the ending video 'skits' that accompany the ending credits when you complete any course in the standard Outrun modes (each course has a different video 'skit') appear to be missing??. These are present in the Outrun Online Arcade that was released on the Xbox 360 and PS3 and I believe Outrun 2 Coast 2 coast on the PS2 and Xbox do you have plans to add these in a future update?

**Comment by lance8765** [comment]
Are you playing with a non-English language? Because the OR2SP announcer is heard only with English language.

See issue #14.

**Comment by BlockABoots** [comment]
Hi, first of all great work on this mod....I love it!!!!.

I had to check, yeah its defo in English Lang....or though I couldn't see an option to change the lang. Here's a video showing the issue.....

https://youtu.be/ce6N2hNXcLo

Thanks

**Comment by lance8765** [comment]
> Hi, first of all great work on this mod....I love it!!!!.
> 
> I had to check, yeah its defo in English Lang....or though I couldn't see an option to change the lang. Here's a video showing the issue.....
> 
> https://youtu.be/ECAtFF_PC08
> 
> Thanks

... oh. Now i understand. What you're asking for simply does not exist in Coast 2 Coast mode.

**Comment by Tenome** [comment]
Yeah, also the "skits" you mentioned are the endings to Heart Attack in 2SP.

**Comment by emoose** [comment]
The announcer is only there in the "Outrun2SP" mode on the menu, the C2C menus are silent

**Comment by BlockABoots** [comment]
> Yeah, also the "skits" you mentioned are the endings to Heart Attack in 2SP.

Nah there defo in the single player standard outrun mode

**Comment by BlockABoots** [comment]
> The announcer is only there when you switch to "Outrun2SP" mode from the menu, the C2C menus themselves are silent.

Ah yes you are correct. Thank you for highlighting that 👍🏻
