### ISSUE TITLE
[Bug]: Grass particles not displaying / displayed out of camera view

### ISSUE THREAD

**Issue by emoose** [emoose/OutRun2006Tweaks#139]
Noticed when testing C2C PS2/Xbox there were far more grass particles than PC, on PC it seems they only seem to display at certain camera angles.

Not really sure what could be causing it yet, values around the grass particle code seem pretty much identical between all the ports, code is pretty much matching too.

Only hint I've seen is by changing some value that shifts the particles left/right, which seemed to show them spawning much further behind the car than the other ports, didn't really see anything in the code that would cause that though.

Could be some weird timing issue where the particles are spawning where the car was instead of where it actually is, need to look into it more with modded camera.

**Comment by emoose** [comment]
Odd, they don't even display with back-view cam, using side-view cam with particles shifted to right side makes them appear on left side too, pretty weird.

Seems the code that draws it to screen does try scaling vertices for it based on screen res, guess there could be an issue there - doesn't seem to be related to screen ratio though, even playing at 640x480 has them draw only at same weird cam angles as 3840x2160 does.

**Comment by emoose** [comment]
Fixed in commit above, looking into it some more I think the only other particle that might also have same bug is PtclGravel, fortunately that uses the same func as grass so should be fixed by the same code 🐱

**Comment by Tenome** [comment]
What a niche bug, nice find.
