### ISSUE TITLE
[Bug]: Brake Lighting issues in Night Stages like Casino Town

### ISSUE THREAD

**Issue by ChibiDreamweaver** [emoose/OutRun2006Tweaks#144]
### Tweaks version

OutRun2006Tweaks-0.6.1

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

![TestarossaMilkyWay](https://github.com/user-attachments/assets/cd9f1b57-500d-4f7d-885d-14008c3401eb)
![360SpiderCasinoTown](https://github.com/user-attachments/assets/ea64919b-12e5-4ea4-a9b8-d6e535a846b4)
![F50Metropolis](https://github.com/user-attachments/assets/e5566614-c496-450f-9aa6-4977d2b98bbe)
I am not sure if anyone has already found a fix for this issue with certain cars like the F50, 360 Spider, and possibly, Testarossa, whenever they enter night stages like Metropolis, Casino Town, and Milky Way, but I thought to point this issue out though and eventually have someone get a fix for it going.

**Comment by Tenome** [comment]
I've seen this brought up in another thread (think it was also a lighting thread), not gonna go looking through all of them but it was at least brought up before. It'd be nice to see it fixed.

**Comment by emoose** [comment]
Anyone know if those cars have it show properly in arcade versions? Tried looking for videos but couldn't turn anything up.

Looking at it in PIX it seems the model itself is missing half of the light for some reason:

![image](https://github.com/user-attachments/assets/2bef01be-0249-40e7-99f5-bd2f307216df)

Maybe some shader trick is meant to duplicate the other half, but not really sure... (this reminds me of the halved-skybox issue really, possible that whatever tool they used to build/convert the arcade files was missing support for some special parts of the model, and would create models with parts missing instead - total speculation though)

Unfortunately disabling the code that draws those lights also disables the license plate light too, but that light doesn't appear in the model in PIX, not sure if theres some way to only disable the broken parts.

**Comment by Dekaid0011** [comment]
> Anyone know if those cars have it show properly in arcade/console versions? Tried looking for videos but couldn't turn much up.

The F50 looks the same on Lindbergh and Chihiro https://youtu.be/-tqqhfCW89w?t=235 https://youtu.be/4YLzTX14SAA?t=307

**Comment by emoose** [comment]
Ah right, kinda weird choice though, IRL cars don't have it halved or anything: https://youtu.be/kQkii2LzYXQ?t=280
![vivaldi_2024-09-21_18-46-07](https://github.com/user-attachments/assets/a894fcaa-c6f6-4b1a-b7e5-c5ab7604405a)

If C2C already matches arcade for this then it's kinda out-of-scope for tweaks, maybe if model mods are ever figured out somebody could remodel them.

**Comment by Dekaid0011** [comment]
> Ah right, kinda weird choice though, IRL cars don't have it halved or anything: https://youtu.be/kQkii2LzYXQ?t=280 ![vivaldi_2024-09-21_18-46-07](https://private-user-images.githubusercontent.com/1755499/369638833-a894fcaa-c6f6-4b1a-b7e5-c5ab7604405a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDEzODEsIm5iZiI6MTcyNjk0MTA4MSwicGF0aCI6Ii8xNzU1NDk5LzM2OTYzODgzMy1hODk0ZmNhYS1jNmY2LTRiMWEtYjdlNS1jNWFiNzYwNDQwNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMTc1MTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTYxMjBmZjFkNzdlODFkZTU0ZmE5MzAyNWVmYTc2Y2E4ODZiMDg2NTZiZjVmNWUwMzYxMzgzNmE4ZGQ1NzJhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.L8dCODMAEQEKsazkCUP_L88uLd1URJv0a4Wc1fhwHmU)
> 
> If C2C already matches arcade for this then it's kinda out-of-scope for tweaks, maybe if model mods are ever figured out somebody could remodel them.

That's an F40 which does light up the brake lights like that on nighttime stages, but I also couldn't find any images on the F50 or 360 that had the brake lights light up like that, tho I also never owned one myself. LOL

**Comment by emoose** [comment]
Ah yeah, swear I was looking for F50 when I found that lol...

https://www.meritpartners.com/f50 does have a pic of it fully lit if you scroll down, but there does kinda look like some line in the middle there

Found pics of some other Ferraris using split lights too, so maybe is intended after all
![image](https://github.com/user-attachments/assets/7d747a62-916c-42b9-b01d-29e6cb70d379)

**Comment by Dekaid0011** [comment]
> Ah yeah, swear I was looking for F50 when I found that lol...
> 
> https://www.meritpartners.com/f50 does have a pic of it fully lit if you scroll down (some pretty neat pics there really), but does kinda look like some line in the middle there
> 
> Found pics of some other Ferraris using split lights too, so maybe is intended after all ![image](https://private-user-images.githubusercontent.com/1755499/369640109-7d747a62-916c-42b9-b01d-29e6cb70d379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDI5NDksIm5iZiI6MTcyNjk0MjY0OSwicGF0aCI6Ii8xNzU1NDk5LzM2OTY0MDEwOS03ZDc0N2E2Mi05MTZjLTQyYjktYjAxZC0yOWU2Y2I3MGQzNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMTgxNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI1M2NiZTMwMDZkN2ExZWRhMmU2Yjg5MjE1ZDUwNjc4NDI4NTQ0NjNjNDc5NGFiNjcxYjUzMmY2MDVjMmI4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.X3txlB24mlB0UDO8Wa7vH6qxdpaxuwh79BI3-tpHNiI)

Ah, yea it seems the Enzo, 360 and F50 share the same brake lights and while they are still split on the F50 and 360 I can't find any image that has them light up split like the Enzo...
