### ISSUE TITLE
[Feature Request]: Full Screen 2SP Endings

### ISSUE THREAD

**Issue by ChibiDreamweaver** [emoose/OutRun2006Tweaks#147]
### Describe the feature you'd like to see added

Not sure if someone has already made a thread about this before but I figured to make one.
I would like to see in the future, a setting for FullScreen 2SP endings. As of right now, the only way to achieve this is to change the resolution settings in the configuration file for OutRun 2006 and not tweaks.
Running OutRun in 4K may be a pipe dream for me but hopefully, this feature gets added

**Comment by Tenome** [comment]
That makes three threads requesting this feature lol.

**Comment by lance8765** [comment]
I think we should close the duplicates at this point... #136 is the only one to keep.
