### ISSUE TITLE
[Bug]: Default .ini CDSwitcher includes SFX

### ISSUE THREAD

**Issue by Tenome** [emoose/OutRun2006Tweaks#158]
### Tweaks version

Current

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

Minor thing, but the tracklist you have included with the default .ini has sound effects, sega441, Last Wave, etc. that aren't part of the soundtrack you'd hear while racing.

**Comment by Tenome** [comment]
bumping since I just delete the default tracks from the ini every time now.

**Comment by emoose** [comment]
Should be fixed in ca60f485fbe01d241f74f69faf9dbee5f7788a31, afaik you should be able to replace the default CDTracks entirely in user.ini now too.

**Comment by Tenome** [comment]
Thanks!
