### ISSUE TITLE
Reflections resolution and update rate

### ISSUE THREAD

**Issue by DonelBueno** [emoose/OutRun2006Tweaks#16]
Is it possible to increase the resolution for the reflections on cars? They also update at a lower rate than the rest of the rendering elements.

**Comment by emoose** [comment]
Seem to have something working for the resolution in https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.3.0-3, tested with a couple resolutions and seemed fine all the way to 8192x8192, not sure if it could end up messing up some effect though (there's some stuff to do with "intensity" and "flare" in the reflection code, not sure if they'll scale properly with higher res)

Not sure about update rate yet, are you playing above 60FPS? There were a few times it seemed to update slow for me as well, but looking at it closer it seems fine, not sure what's up with that...

**Comment by DonelBueno** [comment]
Works perfectly, very nice.

About the update rate, I was playing at 144 FPS, but the accelerated textures annoyed me, so I reverted back to 60 FPS. It seems the reflections update at 30 FPS regardless of the framerate, though.

**Comment by espiox** [comment]
I'd appreciate a setting to force reflections to update at 60fps, since I can't get the game running at 120fps for the solution above.
