### ISSUE TITLE
Beta versions (latest: CI automatic builds)

### ISSUE THREAD

**Issue by emoose** [emoose/OutRun2006Tweaks#17]
Builds of the latest commit can be found here: https://github.com/emoose/OutRun2006Tweaks/actions

Just click on the top-most commit shown there, then you can find the `outrun2006tweaks-abcdefg` download listed under `Artifacts`. (may need to sign in to github to download)

---

Github doesn't display pre-release versions on the main page, so this pinned issue will point to the latest version.

If you have any issues with beta versions feel free to make an issue report or reply here.

Current version is 0.3.0-release: https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.3.0-release

Old
 0.3.0-rc3: https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.3.0-3
 0.3.0-rc2: https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.3.0-2
 0.3.0-rc1: https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.3.0

**Comment by DonelBueno** [comment]
Every new feature I tried worked nicely here, great work.

I didn't try .wav files yet.

About the "HideOnlineSigninText", I think it would be better to show the "Sign-in" option while you don't find how to remove the text. The most anoying by far anyway was the "Not Signed In" text, since it flashed extremely fast with higher framerates.

**Comment by emoose** [comment]
Posted 0.3.0-rc2, adds ControllerHotPlug which should let game detect new controllers without needing a restart, kept forgetting to turn it on before launching and it bugged me lol.

>I think it would be better to show the "Sign-in" option while you don't find how to remove the F1 buttom

Yeah probably would look better than just having the button there, changed it in rc2.

**Comment by lance8765** [comment]
This can be closed. The two 0.3.0 appeared on the main page!

**Comment by emoose** [comment]
It still shows as OutRun2006Tweaks 0.2.5 for me on https://github.com/emoose/OutRun2006Tweaks, I think only way to see the pre-release versions is on releases page directly https://github.com/emoose/OutRun2006Tweaks/releases

Will probably release 0.3 proper soon, just got one more thing I'm hoping to add there...

**Comment by lance8765** [comment]
Yeah, i'm an idiot. It shows 0.2.5 but also "+10 releases" right under that and that includes the three release candidate.

**Comment by Belouarrak** [comment]
It took me some time figuring it out since I'm not a file format expert so just for posterity, the dumped .DDS textures are DXT5 format if you want to play around with upscaling and the likes.

**Comment by UserGit-2021** [comment]
> It still shows as OutRun2006Tweaks 0.2.5 for me on https://github.com/emoose/OutRun2006Tweaks, I think only way to see the pre-release versions is on releases page directly https://github.com/emoose/OutRun2006Tweaks/releases
> 
> Will probably release 0.3 proper soon, just got one more thing I'm hoping to add there...

Where can I get uncompressed files?

![изображение](https://github.com/emoose/OutRun2006Tweaks/assets/91757058/b6dbdbce-c981-4da4-999c-6506d7e9debb)

**Comment by DonelBueno** [comment]
> > Where can I get uncompressed files?
> 
> Outrun 20th anniversary box has pretty much all the C2C tracks included with it, can't really include them with the mod, but shouldn't be too difficult to find.
> 
> (The Turbo Outrun songs like Rush a Difficulty seem a bit different in that set though, did find an uncompressed one for Rush a Difficulty that matches C2C but haven't found the other two yet...)

Do you know a good offline flac to wav converter?

**Comment by emoose** [comment]
I just used ffmpeg to handle it, not sure if there's any good GUI tools for it, you can use this bat script if ffmpeg.exe is in the same folder:

```
@echo off
for %%i in (*.flac) do (
    ffmpeg -i "%%i" -c:a pcm_s16le "%%~ni.wav"
)
```

**Comment by DonelBueno** [comment]
Thanks, I have ffmpeg here.
