### ISSUE TITLE
[Bug]: "the procedure entry point _BinkDX9SurfaceType@4 could not be located in the dynamic link library"

### ISSUE THREAD

**Issue by mogchamp2** [emoose/OutRun2006Tweaks#173]
### Tweaks version

0.6.1

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

when i ran the .exe it gave me this error, even when installing the latest redist.
![image](https://github.com/user-attachments/assets/34f8643d-0034-43ef-b130-6b57f13e238c).
after downloading the dll and putting it in the same folder as that i got this error.
![image](https://github.com/user-attachments/assets/5762c670-6c64-4a0d-bc22-fb83598bfe75). 
does anyone have a clue as to what's going on?

**Comment by emoose** [comment]
Maybe wrong binkw32.dll version, that should be included with your game really.

Here's the one from my install, but if you were missing this you could be missing other game files: 
[binkw32.zip](https://github.com/user-attachments/files/17622820/binkw32.zip)

**Comment by mogchamp2** [comment]
thanks, worked like a charm. i've ran the game before and it was fine, so that file could have just messed up somehow.
