### ISSUE TITLE
[Bug]:  Tweaks v0.6.1 - ending cutscenes restoration or NO [ridiculous] ending cutscenes?

### ISSUE THREAD

**Issue by Kimet1970** [emoose/OutRun2006Tweaks#177]
### Tweaks version

Tweaks 0.6.1

I applied all tweaks for 0.6.1 version...
But the ridiculous ending cutscenes with histerical girls against the driver... dissapered.
I get only a final scene qith the car driftting and a  message as "Try again"... or something in this line... 
No objection!! Actually that scenes are unnecessary and ridiculous!!
But I'm doing something wrong?

best regards...

**Comment by Tenome** [comment]
Were you on the wrong mode? Cutscenes are for the original 2SP, not 2006. They worked for me last I tried.

**Comment by Sonic-TV** [comment]
Go to the 2SP Mode and finish a round if you want to see the ending cutscenes.

**Comment by Kimet1970** [comment]
Yes! You are right! I could get the final cutscenes... and there was not a ridiculous cutscene with a girl doing a a scandal...
A funny scene with moving Pascoa's island statues....
Were they replaced?

**Comment by Tenome** [comment]
Try different goals, they each have their own endings.
