### ISSUE TITLE
Crash when booting with Proton/Wine

### ISSUE THREAD

**Issue by olivil** [emoose/OutRun2006Tweaks#19]
I'm trying to play this tweak on my Steam Deck using Proton. The game starts, create OutRun2006Tweaks.log where it parses the options from the .ini then suddenly exits with no further error. The last line of my log is [Info] - ControllerHotPlug: false.
I have the VC 2017 redist installed, wondering if maybe I am missing some other requirement? Thanks.

**Comment by emoose** [comment]
>I have the VC 2017 redist installed, wondering if maybe I am missing some other requirement? Thanks.

Is that the latest one from https://aka.ms/vs/17/release/vc_redist.x86.exe? There was a crash issue before if using a slightly older VC2017 redist, thought I'd added a workaround for that but maybe it's still an issue.

Other than that there shouldn't really be any other requirement, unless maybe the game requires something else that your proton  is missing, are you able to launch the game without tweaks setup?

**Comment by olivil** [comment]
Thank you for replying so quickly! The redist I installed via Protontricks which should download the version you linked straight from MS's servers but I don't know for sure what exact version I have. Forgot to mention but the game does run without the tweak, and both of your fixes do work and I have not noticed a difference between them in performance! :) Consider this issue fixed. Thanks a lot!
