### ISSUE TITLE
[Bug]: UILetterboxing + dgvoodoo not cropping with new experimental Overlay Enabled

### ISSUE THREAD

**Issue by Zoukambada** [emoose/OutRun2006Tweaks#192]
### Tweaks version

outrun2006tweaks-fcc1e3e23d4f53919f1871e8f3a04855adf10b70

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

# UIScalingMode "1" / UILetterboxing"1" + dgvoodoo (2.83) not cropping with new experimental Overlay Enabled
This has been reported before but it was taking too much attention for a bug in a issue dedicated to [GUI/overlay ideas (issue#180)](https://github.com/emoose/OutRun2006Tweaks/issues/180). So lets focus this bug here:

## History
1. https://github.com/emoose/OutRun2006Tweaks/issues/180#issuecomment-2542721874
> ![image](https://github.com/user-attachments/assets/f7796839-974f-4535-b5eb-bbfa1e08fc2b)
> With the latest tweaks from this issue, I get these white borders around the UI. It starts just after it boots, at the logo and intro screen.
> I tried to disable ReShade but it didn't effect it. I tried with a fresh tweaks install and same thing happened, so I downgraded to the stable version and voiola.
> I also can't drag and drop to reorganize the Notification menu. The other menus I can.

2. https://github.com/emoose/OutRun2006Tweaks/issues/180#issuecomment-2542835939
> When ReShade is disabled it still happens... But you are right I forgot to say that I use dgvoodoo (latest) so the game can ran in dx11 (the performance is better for me that I use ReShade). My card is RTX 4060. Below screenshots with the DLLs of DX from dgvoodoo and its settings. (ReShade uses dxgi but as I told you even if I remove the reshade dll, the bug persists). If I disable dgvoodoo2 and overlay is enabled, the bug is gone. ![image](https://private-user-images.githubusercontent.com/8125662/395745845-c56a1fdd-f1aa-4ecd-bbe7-241c1a1d7c1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTA4MTAsIm5iZiI6MTczNDMxMDUxMCwicGF0aCI6Ii84MTI1NjYyLzM5NTc0NTg0NS1jNTZhMWZkZC1mMWFhLTRlY2QtYmJlNy0yNDFjMWExZDdjMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMDA1NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZjZmJmZDFkNjhiMjU1NmFkNjdiOWM3NzcxZmYzMzA1ZGNjMWNhNjRlYjgyNjU1YzA5MTdjYzgzN2RmZmY5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4AvmR4_Qu4vknVTuzfrCTvd0WDefivWP33ypM7FP9fk) ![image](https://private-user-images.githubusercontent.com/8125662/395745846-eb1bbc5f-8d6c-4178-a318-cf074605e642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTA4MTAsIm5iZiI6MTczNDMxMDUxMCwicGF0aCI6Ii84MTI1NjYyLzM5NTc0NTg0Ni1lYjFiYmM1Zi04ZDZjLTQxNzgtYTMxOC1jZjA3NDYwNWU2NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMDA1NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg4NmI2MDgwNWI3NWZlYTAzMThhZDQ2NjBhNmE0ZDQzZWZlYmVlNjYyODk3NDA2MmMyMDNkODE3M2U2NWI4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RK_14PhR1_bzHAXW4f3tnUEHJ0QYskVzND9nc3XrXqs)
> 
> Before posting this reply, I just tried other things... I left only the d3d9.dll and dgvoodo to its default settings (without reshade) and the same bug persists. I forgot to say that when I enter the flagman menu missions, the bug goes away for good. If I go back to main menu for example, its still gone. Even the intro movie is not affected after entering Flagman menu. Also if I enter OutRun2SP menu, the bug is gone too.

3. https://github.com/emoose/OutRun2006Tweaks/issues/180#issuecomment-2543176079
> > Hm, could you see if this build works any better with dgvoodoo? Maybe I wasn't creating letterbox resources properly
> > [or2006tweaks-letterboxtest.zip](https://github.com/user-attachments/files/18134519/or2006tweaks-letterboxtest.zip)
> 
> @emoose I dropped the new dinput8.dll and replaced it, it didn't take any effect. The bug still remains. FYI, like the other build, soon as it boots the bug starts. (Tested with dgvoodoo with and without ReShade).
> 
> Then for the god's sake I tried one of the firsts imgui builds from this [post](https://github.com/emoose/OutRun2006Tweaks/issues/97#issuecomment-2525354463). When I boot it seems it's fixed but when I press F11 to open the overlay, the bug appears. Here the overlay needs to open just once to trigger the bug, in the other it's already there from the begining.
> 
> > ![imagen](https://private-user-images.githubusercontent.com/191665624/395756411-00c1ab2f-7949-40f7-9de0-fa221319aeb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTMwMTcsIm5iZiI6MTczNDE5MjcxNywicGF0aCI6Ii8xOTE2NjU2MjQvMzk1NzU2NDExLTAwYzFhYjJmLTc5NDktNDBmNy05ZGUwLWZhMjIxMzE5YWViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNjExNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTVlMmFhZjNlZTgxNTZhZDZmN2M3NmE1ZDAwNzlmNjM2YjQ0MDJlYjM5ODM2ZGRhYWNmOTgzMjkyZWNjN2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rqyVo2nrd2iAkOwM4Rl7heEqVJJ5pw3ItbLoQNpnsmA)
> > make sure you have this checkbox activated
> 
> @nuexzz I checked here. It didn't make a difference, it was already enabled.

## New info...
I don't know if it has something to do with the bug, but if you pay attention the OutRun2006Tweaks.log registers that I had set antialiasing 2 but in my outrun2006.ini it is set to 0:

**OutRun2006Tweaks.log** registers these:
```
[2024-12-15 21:53:42.796] [info] GameDefaultConfigOverride: default resolution set to 1920x1080, windowed enabled, fog enabled, antialiasing 2
[2024-12-15 21:53:42.796] [info] GameDefaultConfigOverride: apply successful
```
and my **OutRun2006Tweaks.ini** settings:
`AutoDetectResolution = true`

While my **outrun2006.ini** settings:
```
DX/ADAPTER = 0
DX/RES/WIDTH = 1920
DX/RES/HEIGHT = 1080
DX/ANTIALIASING = 0
DX/FOG = 1
LANGUAGE = 0
DX/WINDOWED = 1
```

**Comment by emoose** [comment]
Hm might be fixed in https://github.com/emoose/OutRun2006Tweaks/actions/runs/12346871367, that seems to get letterboxing to show for me with dgvoodoo again anyway, but haven't really tested it that much yet, not sure if UILetterboxing = 2 might have issues when in-game or not
