### ISSUE TITLE
[Bug]: Flashing Lights in Metropolis, Ghost Forest and Milcky Way

### ISSUE THREAD

**Issue by BluryBisony9** [emoose/OutRun2006Tweaks#198]
### Tweaks version

v.6.1

[OutRun2006Tweaks.log](https://github.com/user-attachments/files/18266513/OutRun2006Tweaks.log)

just a lot offlashing lights all over the level

https://github.com/user-attachments/assets/7e01854c-e8e4-4b84-a1c7-fb4e27298565

Its really annoying.
also for some levels like national park the skyline is missing
thank you all for reviving this gem,
guys you don't know what this game means to me

**Comment by emoose** [comment]
Are you on an intel GPU? Another user reported same thing with theirs, iirc they were able to fix it by using dgvoodoo with the game: https://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_84.zip
IIRC you just extract the files from the MS/x86/ folder into the game dir

**Comment by BluryBisony9** [comment]
> Are you on an intel GPU? Another user reported same thing with theirs, iirc they were able to fix it by using dgvoodoo with the game: https://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_84.zip Think you just extract the files from the MS/x86/ folder into the game dir

try it it didn't work

**Comment by Zoukambada** [comment]
> Alright so I solved it by downloading the audio fix [aka.ms/vs/17/release/vc_redist.x86.exe](https://aka.ms/vs/17/release/vc_redist.x86.exe) if it doesn't fix it try downloading [dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_84.zip](https://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_84.zip)

@emoose I know that you recommend in the readme.md that everyone downloads the VC_Redist... maybe also describe that _if you have X and Y bugs its because you didn't bla bla bla, do this to fix it_ and mention these flashing bugs and also this issue number.
