### ISSUE TITLE
Feature Request - Port the exclusives levels from the japanese  xbox version

### ISSUE THREAD

**Issue by FuxorLuck** [emoose/OutRun2006Tweaks#28]
I am talking about these levels

https://www.youtube.com/watch?v=FKzTZ8nyIV4

https://www.youtube.com/watch?v=5CjR_eyUdTQ

In order to avoid copyright issues, I am requesting a tool that will be able to export the level files from the japanese xbox disc that I own and will convert the files to be compatible with OutRun2006Tweaks

Thank you

**Comment by lance8765** [comment]
Duplicate of #3... also weren't they in all versions? They were "only" fixed/improved in Japan.

**Comment by Levine91** [comment]
> Duplicate of #3... also weren't they in all versions? They were "only" fixed/improved in Japan.

Nope, the bonus stages from Daytona USA 2 and Scud Racer are only in the Japanese Xbox version for whatever reason.

**Comment by lance8765** [comment]
> > Duplicate of #3... also weren't they in all versions? They were "only" fixed/improved in Japan.
> 
> Nope, the bonus stages from Daytona USA 2 and Scud Racer are only in the Japanese Xbox version for whatever reason.

Ehr... no? Read the video descriptions.

**Comment by emmanu888** [comment]
> > Duplicate of #3... also weren't they in all versions? They were "only" fixed/improved in Japan.
> 
> Nope, the bonus stages from Daytona USA 2 and Scud Racer are only in the Japanese Xbox version for whatever reason.

I have the US version of the game, the bonus stages are present and playable.

**Comment by emoose** [comment]
Duplicate of https://github.com/emoose/OutRun2006Tweaks/issues/3
