### ISSUE TITLE
UI still stretched

### ISSUE THREAD

**Issue by Rex000** [emoose/OutRun2006Tweaks#30]
![OutRun2006_ Coast to Coast0](https://github.com/emoose/OutRun2006Tweaks/assets/28770012/53e70a60-ad4b-467e-917c-f7a8ca0b61ec)

I have set 1080p resolution in the config.

**Comment by Joe-Kaze** [comment]
Did you set "UIScalingMode = 1" in the OutRun2006Tweaks.ini?

**Comment by Rex000** [comment]
Sorry my bad I read the instructions on a website rather than on the github page
