### ISSUE TITLE
[FXT features] Bonus cars/songs, SP arcade mode?

### ISSUE THREAD

**Issue by Tenome** [emoose/OutRun2006Tweaks#33]
![FXTConfig_hG4jxVmduK](https://github.com/emoose/OutRun2006Tweaks/assets/12216081/f95ab576-39a8-4b34-bd70-e6ff3eca94fa)
https://www.youtube.com/watch?v=sCdbClzjnVk

I'm just requesting this so I'll never have to use the janky FXT hack again. I'm not sure if they were hacked in from the arcade version though. Thanks for your work!

**Comment by lance8765** [comment]
I wish i could give you 50 likes just for calling FXT "janky" lmao.

As for the bonus songs, currently the only way to enjoy them is to use the included CDSwitcher feature.

**Comment by chanunnaki** [comment]
> I wish i could give you 50 likes just for calling FXT "janky" lmao.
> 
> As for the bonus songs, currently the only way to enjoy them is to use the included CDSwitcher feature.

FXT itself wasn't the jankiest, but all the hoops you had to jump through to limit the framerate with special K and the broken anti-aliasing... oh wait... it was janky as hell. Never mind.

**Comment by Tenome** [comment]
> I wish i could give you 50 likes just for calling FXT "janky" lmao.
> 
> As for the bonus songs, currently the only way to enjoy them is to use the included CDSwitcher feature.

I appreciate the work he did trying to wrangle in Outrun 2006, but man is it janky. I just tried it on Windows 10 and it just constantly forced windowed mode and opened the driver's license menu at a rapid fire, even after I limited it to 60FPS. 

I also liked the custom track order mod, I used to always play the shuttle mission second.

**Comment by lance8765** [comment]
> > I wish i could give you 50 likes just for calling FXT "janky" lmao.
> > As for the bonus songs, currently the only way to enjoy them is to use the included CDSwitcher feature.
> 
> I appreciate the work he did trying to wrangle in Outrun 2006, but man is it janky. I just tried it on Windows 10 and it just constantly forced windowed mode and opened the driver's license menu at a rapid fire, even after I limited it to 60FPS.
> 
> I also liked the custom track order mod, I used to always play the shuttle mission second.

It's also a lot more resource demanding than Tweaks. C'mon, if a game from motherfriggin' 2006 can't run on a old gaming rig from a couple of years later (it also runs well on a Vaio from twelve years ago!) , ask yourself a couple of questions...

**Comment by ViperAcidZX** [comment]
> > I wish i could give you 50 likes just for calling FXT "janky" lmao.
> > As for the bonus songs, currently the only way to enjoy them is to use the included CDSwitcher feature.
> 
> FXT itself wasn't the jankiest, but all the hoops you had to jump through to limit the framerate with special K and the broken anti-aliasing... oh wait... it was janky as hell. Never mind.

To be honest, I was contemplating on making a new request here to see if its possible to backport some of the FXT-specific fixes for the game (with Howards help, of course) because I could see this as the open-source evolution/successor to FXT Edition.

**Comment by lance8765** [comment]
What "fixes" from FXT are still missing from Tweaks?

**Comment by ViperAcidZX** [comment]
FXT Edition fixes the broken Horn button which does nothing at all when pressed by default but there is a button/key for it in the Options under the keyboard/controller configuration menu. Apparently FXT restores two more music tracks that were omitted in the US version (although the music player in Tweaks could possibly add those).

**Comment by lance8765** [comment]
> FXT Edition fixes the broken Horn button which does nothing at all when pressed by default but there is a button/key for it in the Options under the keyboard/controller configuration menu. Apparently FXT restores two more music tracks that were omitted in the US version (although the music player in Tweaks could possibly add those). It also has a pseudo "Arcade Mode" function that mimics OutRun 2 SP by hiding the other menus.

Well if you look at the commits, the Horn will come in a future version... what are the two music tracks? Are those part of the four tracks from the Japanese PS2 version?

**Comment by Tenome** [comment]
> > FXT Edition fixes the broken Horn button which does nothing at all when pressed by default but there is a button/key for it in the Options under the keyboard/controller configuration menu. Apparently FXT restores two more music tracks that were omitted in the US version (although the music player in Tweaks could possibly add those). It also has a pseudo "Arcade Mode" function that mimics OutRun 2 SP by hiding the other menus.
> 
> Well if you look at the commits, the Horn will come in a future version... what are the two music tracks? Are those part of the four tracks from the Japanese PS2 version? I can't find any info about that.

I haven't installed FXT in forever, but a cursory search tells me it might be Passing Breeze [H.] Arrange Ver., Splash Wave J Arrange Ver., Rush a Difficulty J Arrange Ver., Lift You Up!. I also have a sound mod for FXT titled Japan Exclusive Tracks.

![TOTALCMD64_uN74ctvUgV](https://github.com/emoose/OutRun2006Tweaks/assets/12216081/c72a0a05-bb59-4672-b245-793d9e414360)

**Comment by lance8765** [comment]
This is weird, because it's not mentioned anywhere, not even on sites like The Cutting Room Floor (sections for OR2 are mostly empty lol)

I'm starting to think he wrote about the "removed" tracks without knowing what he was talking about.

**Comment by Tenome** [comment]
Well, whatever! Just load the Outrun anniversary box and be done with it (though ideally, LOOP point metadata can also be integrated so you don't have to generate 40 minute loops).

On the subject of FXT features, Howard has a [Course Editor ](http://forum.arcadecontrols.com/index.php/topic,130891.msg1681494.html#msg1681494)tool that lets you change the order of maps. I haven't tested if this works with just Tweaks, though, but integrating this as a feature would also be cool. It modifies the script files, though, so it might be harder than just simply arranging the order in an ini. It's buried in the Outrun hacking forum so I'll repost it here. If anyone tries it and it works, let us know.

https://www.youtube.com/watch?v=8J1I7xaxZvM

**Comment by lance8765** [comment]
> Well, whatever! Just load the Outrun anniversary box and be done with it (though ideally, LOOP point metadata can also be integrated so you don't have to generate 40 minute loops).

I tested the four Japanese tracks to report a problem with fonts (you got a red heart instead of "H." in Passing Breeze [H.] Arrange Ver.)

For now the CDSwitcher is the best alternative if the tracks cannot be fully implemented in-game like on PS2.
