### ISSUE TITLE
[Feature Request] Random track for mid-race CDSwitcher

### ISSUE THREAD

**Issue by chanunnaki** [emoose/OutRun2006Tweaks#35]
Currently building a FLAC audio playlist for use in this game.

Would be great to have a shortcut for RANDOM TRACK if possible!

Random track on the music selection screen is already available natively, so I hope it won't be too much of a hassle or difficult to be implemented.

**Comment by chanunnaki** [comment]
I'm in the process of importing the 207 track list of the 20th Anniversary box into the game.

Random track listing would be highly, highly appreciate. <3

**Comment by chanunnaki** [comment]
Completed track listing for all 11 discs of OutRun 20th Anniversary Box:

\Disc 1\01 Magical Sound Shower.flac = MAGICAL SOUND SHOWER - Out Run (1986 Arcade)
\Disc 1\02 Passing Breeze.flac = PASSING BREEZE - Out Run (1986 Arcade)
\Disc 1\03 Splash Wave.flac = SPLASH WAVE - Out Run (1986 Arcade)
\Disc 1\04 Last Wave.flac = LAST WAVE - Out Run (1986 Arcade)
\Disc 1\05 Vivacious = VIVACIOUS - Turbo Out Run (1986 Arcade)
\Disc 1\06 Shake the Street.flac = Shake the Street - Turbo Out Run (1989 Arcade)
\Disc 1\07 A Huge Pile of Parts.flac = A Huge Pile of Parts - Turbo Out Run (1989 Arcade)
\Disc 1\08 Rush a Difficulty.flac = Rush a Difficulty - Turbo Out Run (1989 Arcade)
\Disc 1\09 Who Are You.flac = Who Are You - Turbo Out Run (1989 Arcade)
\Disc 1\10 Keep Your Heart.flac = Keep Your Heart - Turbo Out Run (1989 Arcade)
\Disc 1\11 Checker Flag.flac = Checker Flag - Turbo Out Run (1989 Arcade)
\Disc 1\12 Easy Going.flac = Easy Going - Turbo Out Run (1989 Arcade)

\Disc 2\01 Mega Driver.flac = Mega Driver - OutRunners (1993 Arcade)
\Disc 2\02 Pre Stage.flac = Pre Stage - OutRunners (1993 Arcade)
\Disc 2\03 Checker Point.flac = Checker Point - OutRunners (1993 Arcade)
\Disc 2\04 Game Start.flac = Game Start - OutRunners (1993 Arcade)
\Disc 2\05 Magical Sound Shower (1993).flac = Magical Sound Shower (1993) - OutRunners (1993 Arcade)
\Disc 2\06 Passing Breeze (1993).flac = Passing Breeze (1993) - OutRunners (1993 Arcade)
\Disc 2\07 Splash Wave (1993).flac = Splash Wave (1993) - OutRunners (1993 Arcade)
\Disc 2\08 Picture The Rivers.flac = Picture The Rivers - OutRunners (1993 Arcade)
\Disc 2\09 Blow Your Cool.flac = Blow Your Cool - OutRunners (1993 Arcade)
\Disc 2\10 Looking for the Rainbow.flac = Looking for the Rainbow - OutRunners (1993 Arcade)
\Disc 2\11 Speed King.flac = Speed King - OutRunners (1993 Arcade)
\Disc 2\12 Adventure.flac = Adventure - OutRunners (1993 Arcade)
\Disc 2\13 Sonic Control.flac = Sonic Control - OutRunners (1993 Arcade)
\Disc 2\14 Check Point.flac = Check Point - OutRunners (1993 Arcade)
\Disc 2\15 Grand Canyon.flac = Grand Canyon - OutRunners (1993 Arcade)
\Disc 2\16 San Francisco.flac = San Francisco - OutRunners (1993 Arcade)
\Disc 2\17 South America.flac = South America - OutRunners (1993 Arcade)
\Disc 2\18 Niagara Falls.flac = Niagara Falls - OutRunners (1993 Arcade)
\Disc 2\19 Hawaii.flac = Hawaii - OutRunners (1993 Arcade)
\Disc 2\20 Pacific Ocean Crossway Bridge.flac = Pacific Ocean Crossway Bridge - OutRunners (1993 Arcade)
\Disc 2\21 Spain.flac = Spain - OutRunners (1993 Arcade)
\Disc 2\22 Atrantic Ocean Underwater Tunnel.flac = Atrantic Ocean Underwater Tunnel - OutRunners (1993 Arcade)
\Disc 2\23 Switzerland.flac = Switzerland - OutRunners (1993 Arcade)
\Disc 2\24 China.flac = China - OutRunners (1993 Arcade)
\Disc 2\25 Japan.flac = Japan - OutRunners (1993 Arcade)
\Disc 2\26 Hong Kong.flac = Hong Kong - OutRunners (1993 Arcade)
\Disc 2\27 Egypt.flac = Egypt - OutRunners (1993 Arcade)
\Disc 2\28 Mediterranean Sea.flac = Mediterranean Sea - OutRunners (1993 Arcade)
\Disc 2\29 France.flac = France - OutRunners (1993 Arcade)
\Disc 2\30 Germany.flac = Germany - OutRunners (1993 Arcade)
\Disc 2\31 Jingle Bells [Secret Track].flac = Jingle Bells [Secret Track] - OutRunners (1993 Arcade)
\Disc 2\32 Final Stage.flac = Final Stage - OutRunners (1993 Arcade)
\Disc 2\33 Dream Flying.flac = Dream Flying - OutRunners (1993 Arcade)
\Disc 2\34 Meaning of the Light - Game Over.flac = Meaning of the Light - Game Over - OutRunners (1993 Arcade)
\Disc 2\35 Last Wave (1993).flac = Last Wave (1993) - OutRunners (1993 Arcade)

\Disc 3\01 Opening Jingle.flac = Opening Jingle - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\02 Opening.flac = Opening - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\03 Magical Sound Shower.flac = Magical Sound Shower - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\04 Passing Breeze.flac = Passing Breeze - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\05 Splash Wave.flac = Splash Wave - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\06 Risky Ride.flac = Risky Ride - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\07 Shiny World.flac = Shiny World - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\08 Night Flight.flac = Night Flight - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\09 Life Was a Bore.flac = Life Was a Bore - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\10 Ending-A.flac = Ending-A - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\11 Ending-B.flac = Ending-B - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\12 Ending-C.flac = Ending-C - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\13 Ending-D.flac = Ending-D - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\14 Ending-E.flac = Ending-E - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)
\Disc 3\15 Last Wave.flac = Last Wave - OutRun 2/SP/SDX/DX (2003 - 2006 Arcade)

\Disc 4\01 Magical Sound Shower.flac = Magical Sound Shower - Out Run (1987 SEGA Mark III - PSG Sound Ver.)
\Disc 4\02 Passing Breeze.flac = Passing Breeze - Out Run (1987 SEGA Mark III - PSG Sound Ver.)
\Disc 4\03 Splash Wave.flac = Splash Wave - Out Run (1987 SEGA Mark III - PSG Sound Ver.)
\Disc 4\04 Last Wave.flac = Last Wave - Out Run (1987 SEGA Mark III - PSG Sound Ver.)
\Disc 4\05 Magical Sound Shower.flac = Magical Sound Shower - Out Run (1987 SEGA Mark III - FM Sound Ver.)
\Disc 4\06 Passing Breeze.flac = Passing Breeze - Out Run (1987 SEGA Mark III - FM Sound Ver.)
\Disc 4\07 Splash Wave.flac = Splash Wave - Out Run (1987 SEGA Mark III - FM Sound Ver.)
\Disc 4\08 Last Wave.flac = Last Wave - Out Run (1987 SEGA Mark III - FM Sound Ver.)
\Disc 4\09 Vivacious.flac = Vivacious - Turbo Out Run (1989 FM Towns)
\Disc 4\10 Shake the Street.flac = Shake the Street - Turbo Out Run (1989 FM Towns)
\Disc 4\11 A Huge Pile of Parts.flac = A Huge Pile of Parts - Turbo Out Run (1989 FM Towns)
\Disc 4\12 Rush a Difficulty.flac = Rush a Difficulty - Turbo Out Run (1989 FM Towns)
\Disc 4\13 Who Are You.flac = Who Are You - Turbo Out Run (1989 FM Towns)
\Disc 4\14 Keep Your Heart.flac = Keep Your Heart - Turbo Out Run (1989 FM Towns)
\Disc 4\15 Checker Flag.flac = Checker Flag - Turbo Out Run (1989 FM Towns)
\Disc 4\16 Easy Going.flac = Easy Going - Turbo Out Run (1989 FM Towns)

\Disc 5\01 Magical Sound Shower.flac = Magical Sound Shower - Out Run 3-D (1989 SEGA Master System - PSG Sound Ver.)
\Disc 5\02 Shining Wind [original].flac = Shining Wind (original) - Out Run 3-D (1989 SEGA Master System - PSG Sound Ver.)
\Disc 5\03 Color Ocean [original].flac = Color Ocean (original) - Out Run 3-D (1989 SEGA Master System - PSG Sound Ver.)
\Disc 5\04 Midnight Highway [original].flac = Midnight Highway (original) - Out Run 3-D (1989 SEGA Master System - PSG Sound Ver.)
\Disc 5\05 Last Wave.flac = Last Wave - Out Run 3-D (1989 SEGA Master System - PSG Sound Ver.)
\Disc 5\06 Magical Sound Shower.flac = Magical Sound Shower - Out Run 3-D (1989 SEGA Master System - FM Sound Ver.)
\Disc 5\07 Shining Wind [original].flac = Shining Wind (original) - Out Run 3-D (1989 SEGA Master System - FM Sound Ver.)
\Disc 5\08 Color Ocean [original].flac = Color Ocean (original) - Out Run 3-D (1989 SEGA Master System - FM Sound Ver.)
\Disc 5\09 Midnight Highway [original].flac = Midnight Highway (original) - Out Run 3-D (1989 SEGA Master System - FM Sound Ver.)
\Disc 5\10 Last Wave.flac = Last Wave - Out Run 3-D (1989 SEGA Master System - FM Sound Ver.)
\Disc 5\11 Magical Sound Shower.flac = Magical Sound Shower - Out Run (1990 PC-Engine)
\Disc 5\12 Passing Breeze.flac = Passing Breeze - Out Run (1990 PC-Engine)
\Disc 5\13 Splash Wave.flac = Splash Wave - Out Run (1990 PC-Engine)
\Disc 5\14 Last Wave.flac = Last Wave - Out Run (1990 PC-Engine)
\Disc 5\15 Magical Sound Shower.flac = Magical Sound Shower - Out Run (1991 Game Gear)
\Disc 5\16 Passing Breeze.flac = Passing Breeze - Out Run (1991 Game Gear)
\Disc 5\17 Splash Wave.flac = Splash Wave - Out Run (1991 Game Gear)
\Disc 5\18 Last Wave.flac = Last Wave - Out Run (1991 Game Gear)

\Disc 6\01 Magical Sound Shower.flac = Magical Sound Shower - Out Run (1991 Mega Drive)
\Disc 6\02 Passing Breeze.flac = Passing Breeze - Out Run (1991 Mega Drive)
\Disc 6\03 Splash Wave.flac = Splash Wave - Out Run (1991 Mega Drive)
\Disc 6\04 Step on Beat [original].flac = Step on Beat [original] - Out Run (1991 Mega Drive)
\Disc 6\05 Last Wave.flac = Last Wave - Out Run (1991 Mega Drive)
\Disc 6\06 Pit Stop (Vivacious).flac = Pit Stop (Vivacious) - Turbo Out Run (1992 Mega Drive)
\Disc 6\07 Main Theme (Shake the Street).flac = Main Theme (Shake the Street) - Turbo Out Run (1992 Mega Drive)
\Disc 6\08 Norma's Theme (A Huge Pile of Parts).flac = Norma's Theme (A Huge Pile of Parts) - Turbo Out Run (1992 Mega Drive)
\Disc 6\09 Insanity (Rush a Difficulty).flac = Insanity (Rush a Difficulty) - Turbo Out Run (1992 Mega Drive)
\Disc 6\10 Funky Run (Who Are You).flac = Funky Run (Who Are You) - Turbo Out Run (1992 Mega Drive)
\Disc 6\11 Highway (Keep Your Heart).flac = Highway (Keep Your Heart) - Turbo Out Run (1992 Mega Drive)
\Disc 6\12 Hairspray (Checker Flag).flac = Hairspray (Checker Flag) - Turbo Out Run (1992 Mega Drive)
\Disc 6\13 Overture (Easy going).flac = Overture (Easy going) - Turbo Out Run (1992 Mega Drive)
\Disc 6\14 Shine Country [original].flac = Shine Country (original) - Turbo Out Run (1992 Mega Drive)
\Disc 6\15 Night Ride [original].flac = Night Ride (original) - Turbo Out Run (1992 Mega Drive)

\Disc 7\01 Title Screen [original].flac = Title Screen (original) - OutRunners (1994 Mega Drive)
\Disc 7\02 Car Select [original].flac = Car Select (original) - OutRunners (1994 Mega Drive)
\Disc 7\03 Travel Seaward [original].flac = Travel Seaward (original) - OutRunners (1994 Mega Drive)
\Disc 7\04 Mega Driver.flac = Mega Driver - OutRunners (1994 Mega Drive)
\Disc 7\05 Pre Stage.flac = Pre Stage - OutRunners (1994 Mega Drive)
\Disc 7\06 Checker Point.flac = Checker Point - OutRunners (1994 Mega Drive)
\Disc 7\07 Game Start [original].flac = Game Start (original) - OutRunners (1994 Mega Drive)
\Disc 7\08 Magical Sound Shower (1993).flac = Magical Sound Shower (1993) - OutRunners (1994 Mega Drive)
\Disc 7\09 Passing Breeze (1993).flac = Passing Breeze (1993) - OutRunners (1994 Mega Drive)
\Disc 7\10 Splash Wave (1993).flac = Splash Wave (1993) - OutRunners (1994 Mega Drive)
\Disc 7\11 Picture the Rivers.flac = Picture the Rivers - OutRunners (1994 Mega Drive)
\Disc 7\12 Blow Your Cool.flac = Blow Your Cool - OutRunners (1994 Mega Drive)
\Disc 7\13 Looking for the Rainbow.flac = Looking for the Rainbow - OutRunners (1994 Mega Drive)
\Disc 7\14 Speed King.flac = Speed King - OutRunners (1994 Mega Drive)
\Disc 7\15 Adventure.flac = Adventure - OutRunners (1994 Mega Drive)
\Disc 7\16 Sonic Control.flac = Sonic Control - OutRunners (1994 Mega Drive)
\Disc 7\17 Grand Canyon.flac = Grand Canyon - OutRunners (1994 Mega Drive)
\Disc 7\18 San Francisco.flac = San Francisco - OutRunners (1994 Mega Drive)
\Disc 7\19 South America.flac = South America - OutRunners (1994 Mega Drive)
\Disc 7\20 Niagara Falls.flac = Niagara Falls - OutRunners (1994 Mega Drive)
\Disc 7\21 Hawaii.flac = Hawaii - OutRunners (1994 Mega Drive)
\Disc 7\22 Pacific Ocean Crossway Bridge.flac = Pacific Ocean Crossway Bridge - OutRunners (1994 Mega Drive)
\Disc 7\23 Spain.flac = Spain - OutRunners (1994 Mega Drive)
\Disc 7\24 Atrantic Ocean Underwater Tunnel.flac = Atrantic Ocean Underwater Tunnel - OutRunners (1994 Mega Drive)
\Disc 7\25 Switzerland.flac = Switzerland - OutRunners (1994 Mega Drive)
\Disc 7\26 China.flac = China - OutRunners (1994 Mega Drive)
\Disc 7\27 Japan.flac = Japan - OutRunners (1994 Mega Drive)
\Disc 7\28 Hong Kong.flac = Hong Kong - OutRunners (1994 Mega Drive)
\Disc 7\29 Egypt.flac = Egypt - OutRunners (1994 Mega Drive)
\Disc 7\30 Mediterranean Sea.flac = Mediterranean Sea - OutRunners (1994 Mega Drive)
\Disc 7\31 France.flac = France - OutRunners (1994 Mega Drive)
\Disc 7\32 Germany.flac = Germany - OutRunners (1994 Mega Drive)
\Disc 7\33 Jingle Bells [secret track].flac = Jingle Bells (secret track) - OutRunners (1994 Mega Drive)
\Disc 7\34 Waiting Your Entry [original] from Virtua Racing.flac = Waiting Your Entry (original) from Virtua Racing - OutRunners (1994 Mega Drive)
\Disc 7\35 Beginner Start [original] from Virtua Racing.flac = Beginner Start (original) from Virtua Racing - OutRunners (1994 Mega Drive)
\Disc 7\36 Final Stage.flac = Final Stage - OutRunners (1994 Mega Drive)
\Disc 7\37 Goal [original].flac = Goal (original) - OutRunners (1994 Mega Drive)
\Disc 7\38 Dream Flying.flac = Dream Flying - OutRunners (1994 Mega Drive)
\Disc 7\39 Staff Roll [original].flac = Staff Roll (original) - OutRunners (1994 Mega Drive)
\Disc 7\40 Meaning of the Light - Game Over.flac = Meaning of the Light - Game Over - OutRunners (1994 Mega Drive)
\Disc 7\41 Last Wave (1993).flac = Last Wave (1993) - OutRunners (1994 Mega Drive)

\Disc 8\01 Magical Sound Shower (1996 arrange version).flac = Magical Sound Shower (1996 arrange version) - Out Run (1996 Sega Saturn for "SEGA AGES")
\Disc 8\02 Passing Breeze (1996 arrange version).flac = Passing Breeze (1996 arrange version) - Out Run (1996 Sega Saturn for "SEGA AGES")
\Disc 8\03 Splash Wave (1996 arrange version).flac = Splash Wave (1996 arrange version) - Out Run (1996 Sega Saturn for "SEGA AGES")
\Disc 8\04 Last Wave (1996 arrange version).flac = Last Wave (1996 arrange version) - Out Run (1996 Sega Saturn for "SEGA AGES")
\Disc 8\05 Magical Sound Shower.flac = Magical Sound Shower - Out Run (2001 Dreamcast for "Shenmue II")
\Disc 8\06 Passing Breeze.flac = Passing Breeze - Out Run (2001 Dreamcast for "Shenmue II")
\Disc 8\07 Splash Wave.flac = Splash Wave - Out Run (2001 Dreamcast for "Shenmue II")
\Disc 8\08 Last Wave.flac = Last Wave - Out Run (2001 Dreamcast for "Shenmue II")
\Disc 8\09 Magical Sound Shower.flac = Magical Sound Shower - Out Run (2001 i.mode for "Sonic Cafe")
\Disc 8\10 Passing Breeze.flac = Passing Breeze - Out Run (2001 i.mode for "Sonic Cafe")
\Disc 8\11 Splash Wave.flac = Splash Wave - Out Run (2001 i.mode for "Sonic Cafe")
\Disc 8\12 Magical Sound Shower.flac = Magical Sound Shower - Out Run (2003 Game Boy Advance for "SEGA Arcade Gallery")
\Disc 8\13 Passing Breeze.flac = Passing Breeze - Out Run (2003 Game Boy Advance for "SEGA Arcade Gallery")
\Disc 8\14 Splash Wave.flac = Splash Wave - Out Run (2003 Game Boy Advance for "SEGA Arcade Gallery")
\Disc 8\15 Last Wave.flac = Last Wave - Out Run (2003 Game Boy Advance for "SEGA Arcade Gallery")

\Disc 9\01 Magical Sound Shower (arrange version).flac = Magical Sound Shower (arrange version) - Out Run [3D-AGES] (2004 PlayStation 2 for "SEGA AGES 2500 Vol.13")
\Disc 9\02 Passing Breeze (arrange version).flac = Passing Breeze (arrange version) - Out Run [3D-AGES] (2004 PlayStation 2 for "SEGA AGES 2500 Vol.13")
\Disc 9\03 Splash Wave (arrange version).flac = Splash Wave (arrange version) - Out Run [3D-AGES] (2004 PlayStation 2 for "SEGA AGES 2500 Vol.13")
\Disc 9\04 Last Wave (arrange version).flac = Last Wave (arrange version) - Out Run [3D-AGES] (2004 PlayStation 2 for "SEGA AGES 2500 Vol.13")
\Disc 9\05 Magical Sound Shower (Euro remix).flac = Magical Sound Shower (Euro remix) - OutRun2 (2005 Xbox)
\Disc 9\06 Passing Breeze (Euro remix).flac = Passing Breeze (Euro remix) - OutRun2 (2005 Xbox)
\Disc 9\07 Splash Wave Euro (Euro remix).flac = Splash Wave Euro (Euro remix) - OutRun2 (2005 Xbox)
\Disc 9\08 Risky Ride (guitar mix).flac = Risky Ride (guitar mix) - OutRun2 (2005 Xbox)
\Disc 9\09 Shiny World (prototype).flac = Shiny World (prototype) - OutRun2 (2005 Xbox)
\Disc 9\10 Night Flight (prototype).flac = Night Flight (prototype) - OutRun2 (2005 Xbox)
\Disc 9\11 Night Flight (instrumental).flac = Night Flight (instrumental) - OutRun2 (2005 Xbox)
\Disc 9\12 Life Was a Bore (instrumental).flac = Life Was a Bore (instrumental) - OutRun2 (2005 Xbox)
\Disc 9\13 Last Wave (Euro remix).flac = Last Wave (Euro remix) - OutRun2 (2005 Xbox)

\Disc 10\01 Radiation.flac = Radiation - OutRun 2006 : Coast 2 Coast (2006 PS2/PSP/Xbox/PC)
\Disc 10\02 Night Bird.flac = Night Bird - OutRun 2006 : Coast 2 Coast (2006 PS2/PSP/Xbox/PC)
\Disc 10\03 Shake the Street (2006 arrange version).flac = Shake the Street (2006 arrange version) - OutRun 2006 : Coast 2 Coast (2006 PS2/PSP/Xbox/PC)
\Disc 10\04 Rush a Difficulty (2006 arrange version).flac = Rush a Difficulty (2006 arrange version) - OutRun 2006 : Coast 2 Coast (2006 PS2/PSP/Xbox/PC)
\Disc 10\05 Who Are You (2006 arrange version).flac = Who Are You (2006 arrange version) - OutRun 2006 : Coast 2 Coast (2006 PS2/PSP/Xbox/PC)
\Disc 10\06 Keep Your Heart (2006 arrange version).flac = Keep Your Heart (2006 arrange version) - OutRun 2006 : Coast 2 Coast (2006 PS2/PSP/Xbox/PC)
\Disc 10\07 Passing Breeze [H.] (arrange version).flac = Passing Breeze [H.] (arrange version) - OutRun2 SP (2007 PlayStation 2)
\Disc 10\08 Splash Wave (J arrange version).flac = Splash Wave (J arrange version) - OutRun2 SP (2007 PlayStation 2)
\Disc 10\09 Rush a Difficulty (J arrange version).flac = Rush a Difficulty (J arrange version) - OutRun2 SP (2007 PlayStation 2)
\Disc 10\10 Lift You Up!.flac = Lift You Up! - OutRun2 SP (2007 PlayStation 2)

\Disc 11\01 1991 Mega Drive Rent a Hero Jingle [Magical Sound Shower].flac = 1991 Mega Drive Rent a Hero Jingle (Magical Sound Shower)
\Disc 11\02 1991 Mega Drive Rent a Hero Jingle [Rush a Difficulty].flac = 1991 Mega Drive Rent a Hero Jingle (Rush a Difficulty)
\Disc 11\03 2000 Dreamcast Rent a Hero No. 1 Jingle [Magical Sound Shower].flac = 2000 Dreamcast Rent a Hero No. 1 Jingle (Magical Sound Shower)
\Disc 11\04 1994 Arcade Daytona USA Jingle [Magical Sound Shower].flac = 1994 Arcade Daytona USA Jingle (Magical Sound Shower)
\Disc 11\05 1994 Arcade Daytona USA Jingle [Rush a Difficulty].flac = 1994 Arcade Daytona USA Jingle (Rush a Difficulty)
\Disc 11\06 1994 Arcade Daytona USA Jingle [Adventure].flac = 1994 Arcade Daytona USA Jingle (Adventure)
\Disc 11\07 1995 Sega Saturn Daytona USA Jingle [Magical Sound Shower].flac = 1995 Sega Saturn Daytona USA Jingle (Magical Sound Shower)
\Disc 11\08 1995 Sega Saturn Daytona USA Jingle [Vivacious].flac = 1995 Sega Saturn Daytona USA Jingle (Vivacious)
\Disc 11\09 1995 Sega Saturn Daytona USA Jingle [Rush a Difficulty].flac = 1995 Sega Saturn Daytona USA Jingle (Rush a Difficulty)
\Disc 11\10 1995 Sega Saturn Daytona USA Jingle [Adventure].flac = 1995 Sega Saturn Daytona USA Jingle (Adventure)
\Disc 11\11 2000 Arcade Crackin'DJ ~ 2001 Crackin'DJ Part 2 [Out Run].flac = 2000 Arcade Crackin'DJ - 2001 Crackin'DJ Part 2 (Out Run)
\Disc 11\12 2006 Arcade Virtua Striker 4 Ver.2006 Supporters Song [Magical Sound Shower].flac = 2006 Arcade Virtua Striker 4 Ver.2006 Supporters Song (Magical Sound Shower)
\Disc 11\13 Magical Sound Shower [H.] Version - for ''Crackin'DJ Part 2 Soundtrack''.flac = Magical Sound Shower (H.) Version - for "Crackin'DJ Part 2 Soundtrack"
\Disc 11\14 Passing Breeze for ''Sega Piano Nocturne''.flac = Passing Breeze for "Sega Piano Nocturne"
\Disc 11\15 Passing Breeze for ''Service Games 01''.flac = Passing Breeze for "Service Games 01"
\Disc 11\16 Last Wave [H.] (vocal version) - for ''Outrun2 Sound Tracks -Side B-''.flac = Last Wave (H.) (vocal version) - for "Outrun2 Sound Tracks -Side B-"
\Disc 11\17 Last Wave With....flac = Last Wave With...

**Comment by Tenome** [comment]
I also did the same, so +1 for random.

**Comment by emoose** [comment]
Would a shuffle option in the INI maybe suffice? Adding another combo might make input code a little messy, but adding some kind of shuffle to it shouldn't be too hard, would also let you go back to previous track etc too.

**Comment by chanunnaki** [comment]
> Would a shuffle option in the INI maybe suffice? Adding another combo might make input code a little messy, but adding some kind of shuffle option shouldn't be too hard, would also let you go back to previous track etc too.

Sounds great! any option for something non-sequential would be great with the amount of tracks we've got here. Thanks

**Comment by lance8765** [comment]
Yeah i'm fine with that, too.

**Comment by lance8765** [comment]
@chanunnaki which version of the 20th Anniversary Box did you use? The ones i've found online didn't have those file names...

**Comment by Tenome** [comment]
> @chanunnaki which version of the 20th Anniversary Box did you use? The ones i've found online didn't have those file names...

Just rename them with MP3Tag or whatever.

**Comment by chanunnaki** [comment]
@lance8765 

Here you go: https://gofile.io/d/L1PGdc

**Comment by emoose** [comment]
Added `SwitcherShuffleTracks` setting in https://github.com/emoose/OutRun2006Tweaks/actions/runs/9828465593, build should be up shortly.

**Comment by lance8765** [comment]
You've finally implemented the horn? Holy ****!

**Comment by chanunnaki** [comment]
> Added `SwitcherShuffleTracks` setting in https://github.com/emoose/OutRun2006Tweaks/actions/runs/9828474845, build should be up shortly.

That's cool! Has the function been enabled yet? I tried it, but it doesn't seem to do anything.

**Comment by emoose** [comment]
>It was on your "to do list" (what happened to that, btw?)

Still hoping to get most of those things in the list fixed, seemed a bit messy having that in the main readme though so figured it's better to put them in issues instead.
