### ISSUE TITLE
[OUT-OF-DATE] Looped / Higher Quality Music Replacement Pack

### ISSUE THREAD

**Issue by brad86m** [emoose/OutRun2006Tweaks#38]
Not an issue with the tweaks mod, but I wanted to share, and didn't know where else to do so.

It always bugged me that the music tracks were rather short, and would have long fade-outs and silence for a few seconds before repeating. I think this takes away from the game's overall polish. All versions have this issue. Some worse than others. The PS2 exclusive Japanese 2SP release fixed this issue for a few tracks by correctly looping and extending them to 20+ minutes. However, quality was rather lacking, and they only did this for some of them. Others were the same as in the other ports. The panning for the OutRun 1986 and Turbo OutRun 1989 tracks is also wrong in every version.

I wanted to have a go at fixing these issues, and thankfully come across some great resources that did 99% of the work. For the main OR2/C2C tracks, I used a custom pack from [smashcustommusic.net](https://smashcustommusic.net/game/2799). These are based off of the higher quality Xbox files, and have custom edited loops. I simply repeated those loops when outputting to WAV. Now they are 30+ minutes in length. More than enough for a 15 stage continuous run. This also saved me the trouble of using the lower quality PS2 versions.

With regard to the 1986 & 1989 tracks, I replaced these with accurate MAME rips put together by folks at [vgmrips.net](https://vgmrips.net/packs/)
Similar to the others, I was able to repeat the loop points with VGMPlay and export to 30-minute WAV tracks.

I also updated radio track selection for the new MAME rips.

I adjusted the peak volume so that all tracks are very similar in volume, unlike the original, where the 86-89 tracks are low volume. 
Format is OGG at 350kbps constant bitrate, but have also uploaded a 7GB FLAC version for those that want to make their own OGG conversions, or to use as is.
Simply extract the files to the sound folder, overwriting when prompted. As always, backup your original OGG files. 
I'm sure there are some other audio files that can be improved, but I think this is pretty good for the main stuff. Thanks to those that put custom looped versions together. 

If anyone knows of a more ideal place to share this, then please do :) 

OGG pack download (2.6GB): https://gofile.io/d/yWPr9x
FLAC pack download (7GB): https://gofile.io/d/JQ5xoS
(I have no idea how long they host files from a guest user)

**Comment by lance8765** [comment]
Thanks bud... well i guess this closes my issue regarding the loop points (#8,)

**Comment by DonelBueno** [comment]
Awesome work =)

Are the Xbox audio files you used lossless?

**Comment by lance8765** [comment]
Ahhhh i've just tested the Turbo OutRun tracks... i wonder why they sounded so different on C2C. And i guess that's why the ones available on YouTube were not ripped from that game (except for one, which is the infamous Rush a Difficulty with the missing first seconds)

**Comment by brad86m** [comment]
> Ahhhh i've just tested the Turbo OutRun tracks... i wonder why they sounded so different on C2C. And i guess that's why the ones available on YouTube were not ripped from that game (except for one, which is the infamous Rush a Difficulty with the missing first seconds)
> 
> EDIT: "SEL_14_Rush_a_Difficulty.ogg" is missing the _1989 at the end!

Indeed. Rush 89 doesn't use the 1989 at the end :)

**Comment by lance8765** [comment]
... ok, that's new for me O_o"

**Comment by brad86m** [comment]
Without realising, I included the Guitar version of Rush alongside the others. That track was not in this version of the game. Only 89 and Arrange were. Can just delete the file.

**Comment by Tenome** [comment]
I know that OGG supports loop points, but I didn't know that FLAC did as well (I don't think I've ever seen a player support it). If the FLAC properly loops in-game, that's cool. Thanks.

**Comment by DonelBueno** [comment]
> I know that OGG supports loop points, but I didn't know that FLAC did as well (I don't think I've ever seen a player support it). If the FLAC properly loops in-game, that's cool. Thanks.

He enlarged the tracks to 30+ minutes instead.

**Comment by brad86m** [comment]
> I know that OGG supports loop points, but I didn't know that FLAC did as well (I don't think I've ever seen a player support it). If the FLAC properly loops in-game, that's cool. Thanks.

The loops were created by the members of the site that hosts them. I basically just took those separate parts and repeated the loop a few times within Reaper audio editor to end up with 30 minute tracks :) kept everything in WAV format before finally creating the OGG pack.

**Comment by lance8765** [comment]
> Without realising, I included the Guitar version of Rush alongside the others. That track was not in this version of the game. Only 89 and Arrange were. Can just delete the file.

Huh... where is it? O_o"

**Comment by brad86m** [comment]
> > I know that OGG supports loop points, but I didn't know that FLAC did as well (I don't think I've ever seen a player support it). If the FLAC properly loops in-game, that's cool. Thanks.
> 
> He enlarged the tracks to 30+ minutes instead.

The AM2 team that did the PS2 port of 2SP did the same thing by making the tracks long.

**Comment by brad86m** [comment]
> > Without realising, I included the Guitar version of Rush alongside the others. That track was not in this version of the game. Only 89 and Arrange were. Can just delete the file.
> 
> Huh... where is it? O_o"
Ignore that comment. I confused myself with Risky Ride Guitar track.

**Comment by brad86m** [comment]
> > Without realising, I included the Guitar version of Rush alongside the others. That track was not in this version of the game. Only 89 and Arrange were. Can just delete the file.
> 
> Huh... where is it? O_o"

Ignore that comment. I confused myself with Risky Ride Guitar track.

**Comment by ViperAcidZX** [comment]
Thank you very much for the HQ music pack!

**Comment by Tenome** [comment]
> > > I know that OGG supports loop points, but I didn't know that FLAC did as well (I don't think I've ever seen a player support it). If the FLAC properly loops in-game, that's cool. Thanks.
> > 
> > 
> > He enlarged the tracks to 30+ minutes instead.
> 
> The AM2 team that did the PS2 port of 2SP did the same thing by making the tracks long. I wonder if it is indeed possible to create metadata loop points. Be interesting to see down the line. And to save some space lol

OGG and FLAC both use VORBUS comments for loops, so it should work the same way as looping OGG files. Here's a quick working looped flac I made in Audacity.

![MediaInfo_X5xTPf3ENs](https://github.com/emoose/OutRun2006Tweaks/assets/12216081/a27071f0-ac07-404c-bead-ebb9c872ac05)

**Comment by brad86m** [comment]
> > > > I know that OGG supports loop points, but I didn't know that FLAC did as well (I don't think I've ever seen a player support it). If the FLAC properly loops in-game, that's cool. Thanks.
> > > 
> > > 
> > > He enlarged the tracks to 30+ minutes instead.
> > 
> > 
> > The AM2 team that did the PS2 port of 2SP did the same thing by making the tracks long. I wonder if it is indeed possible to create metadata loop points. Be interesting to see down the line. And to save some space lol
> 
> OGG and FLAC both use VORBUS comments for loops, so it should work the same way as looping OGG files. Here's a quick **working looped** flac I made in Audacity.
> 
> ![MediaInfo_X5xTPf3ENs](https://private-user-images.githubusercontent.com/12216081/347273858-a27071f0-ac07-404c-bead-ebb9c872ac05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjA5NjQsIm5iZiI6MTcyMDYyMDY2NCwicGF0aCI6Ii8xMjIxNjA4MS8zNDcyNzM4NTgtYTI3MDcxZjAtYWMwNy00MDRjLWJlYWQtZWJiOWM4NzJhYzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE0MTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmM2M2ZTM0NjFmMGU0Zjc0ZDgxNjgwNmJkMDIwOTg3Yzc1MmVhYTFjNTEwN2NkMjU0OTkxMGY5NDcxNzNlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FCe8BW_IoXwYsNHYvngdR6LUhseUNkVwkaZiZcg-J74)

You got it to work in-game ? I tried a few looped ogg files myself, and it just ignores the loop point. It would be nice to have the feature working one day.

**Comment by Tenome** [comment]
> You got it to work in-game ? I tried a few looped ogg files myself, and it just ignores the loop point. It would be nice to have the feature working one day.

No, the game doesn't support loop metadata, hence the PR to see if it's maybe possible.

**Comment by Tenome** [comment]
> You got it to work in-game ? I tried a few looped ogg files myself, and it just ignores the loop point. It would be nice to have the feature working one day.

Good news! https://github.com/emoose/OutRun2006Tweaks/commit/2f74dc71e530d3c9a9dee477610029b617e8ffdf

**Comment by ViperAcidZX** [comment]
> > You got it to work in-game ? I tried a few looped ogg files myself, and it just ignores the loop point. It would be nice to have the feature working one day.
> 
> Good news! [2f74dc7](https://github.com/emoose/OutRun2006Tweaks/commit/2f74dc71e530d3c9a9dee477610029b617e8ffdf)

I'm praying for looping OGG support next!

**Comment by chrism69** [comment]
Thanks for this, it's so nice to have the original tracks in higher quality. Any plans to do other versions, like the 2 new 3DS tracks?

**Comment by Tenome** [comment]
@emoose Can we have a sticky thread for music replacements? I'm planning on making some now that FLAC loops are supported but don't want to crib on OP's thread.

**Comment by Left-Empty** [comment]
If brad86m was wondering what the limit at gofile.io may have been, it seems to be the number of downlowded GBs as the FLAC version of his work is now sadly gone.

**Comment by SegaK1d** [comment]
Any chance someone can reupload please? both packs appear to be gone now sadly

**Comment by lance8765** [comment]
> Any chance someone can reupload please? both packs appear to be gone now sadly

I only have the .OGG one i'm afraid.

**Comment by lance8765** [comment]
... what? Instead of reuploading, the issue was closed as completed? <_<"

**Comment by Tenome** [comment]
There's a properly looped FLAC version now. Dunno if Danhanado is waiting to fix something to post it here first, but here's the link anyway.

https://mega.nz/file/XltSBRxR#I1iFTzialJaVuphl1JvayGutLzrP3HOKGvjKiwu128o

**Comment by brad86m** [comment]
> ... what? Instead of reuploading, the issue was closed as completed? <_<"

Sorry about that. Didn't mention I was aware of the new looped music mod was on the way here soon. 
Basically makes mine irrelevant, so no need to re-upload this. 

Proper loop support is far, far better. The only benefit of my tracks were the higher quality MAME rom VGM rips for the 86.89 tracks, but they can be done again and looped with the new method anyway.

**Comment by Left-Empty** [comment]
Thank you for the FLAC loop pack Tenome. I tried it and it seems to work perfectly so far, excepting for the Shiny World default track, which doesn't play in the track select, nor in the game if selected. 
If I fiddle a bit around the menu going a couple of times over it, the game will eventually crash. I wonder if anybody else is experiencing this, and I hesitate to create a dedicated issue for something that is not part of the Tweaks themselves.

**Comment by Tenome** [comment]
Shiny World flacs are missing an underscore in the filename.

**Comment by lance8765** [comment]
Oh... do you think it's better to open a new topic for the updated pack at this point?
