### ISSUE TITLE
Cars Base Shadow Missing

### ISSUE THREAD

**Issue by Sonic-TV** [emoose/OutRun2006Tweaks#39]
![Image_1720284054446](https://github.com/emoose/OutRun2006Tweaks/assets/12370185/9bfcf297-25f1-4e78-98f7-1c2f4c1e6562)
As seen in this image.
Left: 2SP, Right: C2C.
Notice the circled area.

**Comment by brad86m** [comment]
Used to be an issue with the Lindberg version when cranking up the internal resolution. Do you have an AMD card ?

**Comment by espiox** [comment]
Yeah, this has been bothering me too - it makes the car look weird without it.

**Comment by brad86m** [comment]
It is a strange bug. I'm wondering if it has something to do with newer GPUs, since this was also an issue with C2C & 2SP PS2 versions on very old builds of PCSX2, and also the Lindbergh game via TeknoParrot.

**Comment by lance8765** [comment]
> It is a strange bug. I'm wondering if it has something to do with newer GPUs, since this was also an issue with C2C & 2SP PS2 versions on very old builds of PCSX2, and also the Lindbergh game via TeknoParrot.

What do you mean with "newer GPUs"? Anything released months/years after the game? My GPU is a GT440 (formerly had a 8800GT) and the issue is still there. Not sure about TeknoParrot/PCSX2 though.

**Comment by Pepperkid222** [comment]
thank god, i thought i was the only person to notice that it was missing.

**Comment by brad86m** [comment]
Also noticed that Flag Man has a stencil shadow in the PC version instead of a soft shadow. PS2,Xbox, and Arcade have soft.

**Comment by lance8765** [comment]
Just noticed that in the install/uninstall window, the base shadows are definitely there and clearly visible in the screenshots...

**Comment by lance8765** [comment]
Decided to boot OR2SPSDX one more time. Base shadows are there.

**Comment by Tenome** [comment]
Isn't it just a porting issue? The PC version definitely isn't the definitive version, from what I remember (graphically, anyway--the shadows, and the bloom are inferior). If it could be fixed, that'd be cool though.

**Comment by brad86m** [comment]
It's only the PC port that is missing the soft shadow under the car and on flag man. Even the PSP port has them.

**Comment by emoose** [comment]
Might have something for this:

![OR2006C2C_JB72xztY4i](https://github.com/emoose/OutRun2006Tweaks/assets/1755499/f4cf2795-7296-4dfb-965e-e1cf6f113fa0)

Just needed to re-add 4 lines back from Xbox C2C port, not sure why they were removed really.

Xbox port did halve the opacity of it though which made it almost invisible on PC, in pic above I just made it use the opacity value setup for the car unchanged, wonder how it compares with other ports though.

If anyone wants to try it: 
[OutrunTweaks-CalcPeraShadow-fix.zip](https://github.com/user-attachments/files/16165536/OutrunTweaks-CalcPeraShadow-fix.zip)

This also seems to help with #23 since it can mask the stencil shadow issues:
![OR2006C2C_mwOJHyTSbQ](https://github.com/emoose/OutRun2006Tweaks/assets/1755499/bd587086-eece-4f5b-856c-4baf5348f2a2)

**Comment by lance8765** [comment]
Good, good. Nice work as usual!

**Comment by espiox** [comment]
Amazing work, thanks @emoose!

**Comment by DonelBueno** [comment]
Great, it indeed solves issue #23:

![OR2006C2C_2024_07_10_15_46_05_389](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/8e2a4882-4d76-4c47-b4f8-f2c46957ec70)
![OR2006C2C_2024_07_10_15_47_25_499](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/4090b096-39ae-416c-98cd-3389c2b9aa06)

What are the other use cases for these shadows?

**Comment by emoose** [comment]
Looks like the other 2 uses were just the car selection screens, latest commit added those too.

Not sure if the shadowing is maybe too dark with this though, would be interested in any comparisons with the console ports.

**Comment by espiox** [comment]
It definitely looks a bit darker than the console ports, I’ll try and compare properly tomorrow.

**Comment by brad86m** [comment]
> Great, it indeed solves issue #23:
> 
> ![OR2006C2C_2024_07_10_15_46_05_389](https://private-user-images.githubusercontent.com/4239694/347563621-8e2a4882-4d76-4c47-b4f8-f2c46957ec70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjQwMTAsIm5iZiI6MTcyMDcyMzcxMCwicGF0aCI6Ii80MjM5Njk0LzM0NzU2MzYyMS04ZTJhNDg4Mi00ZDc2LTRjNDctYjRmOC1mMmM0Njk1N2VjNzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTg0ODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGY4ZWYzMTcxNjlhYTIxOWNjZjA5MTJkODkxNWRkZjVjZmU0NDU2YTRlZmFjZDUxMjExOTNlODZkYmMxOGRjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AwWWP8pSc3-7edxCN7kyhXdHOhypaRZAlKDm3awUxmw) ![OR2006C2C_2024_07_10_15_47_25_499](https://private-user-images.githubusercontent.com/4239694/347563638-4090b096-39ae-416c-98cd-3389c2b9aa06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjQwMTAsIm5iZiI6MTcyMDcyMzcxMCwicGF0aCI6Ii80MjM5Njk0LzM0NzU2MzYzOC00MDkwYjA5Ni0zOWFlLTQxNmMtOThjZC0zMzg5YzJiOWFhMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTg0ODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGYzNTI5ZjFmN2JmYzhlYjhkZmI5MDZjZGExYjUxYWE3ZDNmYzRiYmQwZWRkMDFhOTYxNzk1MmFiMDY1MWQwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yVttDcLXWWn4EMurWnmnWkiiukH6yFYIRY8TMMdyMrA)
> 
> What are the other use cases for these shadows?

Flag man uses a soft shadow

**Comment by brad86m** [comment]
> Looks like the other 2 uses were just the car selection screens, latest commit added those too.
> 
> Not sure if the shadowing is maybe too dark with this though, would be interested in any comparisons with the console ports.

![fgfgfgf](https://github.com/emoose/OutRun2006Tweaks/assets/84683672/0350dcc9-e824-4573-9ff8-fc5b0195fccb)
Hope that helps

**Comment by Pepperkid222** [comment]
> > Looks like the other 2 uses were just the car selection screens, latest commit added those too.
> > Not sure if the shadowing is maybe too dark with this though, would be interested in any comparisons with the console ports.
> 
> ![fgfgfgf](https://private-user-images.githubusercontent.com/84683672/347960927-0350dcc9-e824-4573-9ff8-fc5b0195fccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Mjc2MTMsIm5iZiI6MTcyMDcyNzMxMywicGF0aCI6Ii84NDY4MzY3Mi8zNDc5NjA5MjctMDM1MGRjYzktZTgyNC00NTczLTlmZjgtZmM1YjAxOTVmY2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE5NDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZTE0NWJmNmIyYjFkYmRkYjA4ZjU5YTllNzA3Y2Q2NTY4ZTU1NGMwYjQ3M2M1ZjBmMzhmYWJkYjUwOWJhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VLTKk_gBX1kaWd4OUHjBniIA45c5q7m8yLJmUfThTlU) Hope that helps
> 
> Also. Always bugged me at how the Xbox and Arcade have that nice sheen look to the back grill on the F50 depending on lighting, but on PS2 and PC it's just black and doesn't seem to have any shine.

Probably because of the shader, since C2C was being developed for Multiple platforms.

**Comment by brad86m** [comment]
They did downgrade the game slightly even for the Xbox with C2C, but that effect remained intact.

**Comment by emoose** [comment]
@brad86m much appreciated! To me it looks like it's pretty much the same as Lindbergh, surprising that Xbox also seems the same since that was using opacity 0.5 which is nearly invisible on PC, guess maybe it's some difference with the renderer.

Will try looking into flag man soon, wonder if it's applied to him specifically or if it's all character models ("robots" in the code), maybe the ending charas are also missing shadow too?

**Comment by lance8765** [comment]
Yes, the ending characters are missing the shadows. https://youtu.be/btQvKBPkQjA?t=298

But the moving Moai statue has it O_o"

**Comment by Outrunner24** [comment]
> Might have something for this:

Doesn't work on my system (Win10 AMD APU). If I replace the dinput8.dll file the game doesn't start anymore.

Congrats on a great mod anyway!

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
found something odd with the sprite. It seems to clip into the geometry and kind of break on hills. 

https://github.com/user-attachments/assets/d5154dc1-6f9a-4fef-9e17-add7219693db

I've seen similar fighting with that small hill before the round a bout in the casino level not shadow related in that level though. If anyone could check if it breaks on the xbox, lindbergh, OTarcade or PS2 would be nice. I don't have those versions atm.

**Comment by Outrunner24** [comment]
> I've seen similar fighting with that small hill before the round a bout in the casino level not shadow related in that level though. 

Yeah even other classics had those glitches, for example Scud Race. You either lift the shadow or lower the road, but it would break the illusion of being there.
