### ISSUE TITLE
Do these tweaks fix the Time Attack times no longer being saved after changing the main executable?

### ISSUE THREAD

**Issue by lance8765** [emoose/OutRun2006Tweaks#4]
Hello, i own a original physical copy of the game.

However, playing it with "NoDVD" executables (not all my computers have optical drives) make the Time Attack times not being saved. It is a old issue that not everybody ever noticed.

I've read this in the changelog:

"FixC2CRankings: fix anti-piracy check that broke C2C ranking scoreboard on Steam release, scores should now save to scoreboard properly"

It this what i'm thinking? My problem is with a original physical copy, not Steam. Does it mean i can play my installed copy without using a DVD and being able to save my times?

Thanks in advance.

ps: another issue i've noticed years ago, is that the original version of "Rush A Difficulty" music from Turbo OutRun doesn't start from the very beginning, but like a couple of seconds later. It is noticeable even when the music restarts from the beginning on long races. The audio file must be replaced. This issue doesn't happen on ALL console versions.

**Comment by emoose** [comment]
If that's the time attack mode in the C2C menus it might be able to help, when I played with the NoDVD version before it seemed to have the same issue with C2C scoreboards not being saved at least, hopefully should help with that ver too.

Looks like the music issue is probably the `Sound\14_Rush_a_Difficulty_1989.ogg` file, seems to start later than in https://www.youtube.com/watch?v=32qRv27c45I at least, wonder if that can just be replaced with a better versio.
(`Sound\SEL_14_Rush_a_Difficulty.ogg` seems to have the beginning part, but think that's just the sample played on selection screen)

**Comment by lance8765** [comment]
Well, the Official Soundtrack version (i mean the 20th Anniversary Box or whatever it's called) is fine, and, like i said in the first post, the console versions are fine, too. Another version that is easy to access is the arcade dump for the SP SDX version (Sega Lindbergh Yellow), the audio files are in .ADX format, can be played with Media Player Classic (not sure about VLC though)

**Comment by lance8765** [comment]
Ok, after managing to fix the startup crashes from the other issue, i tried a Time Attack race... but it still doesn't save my record O_o"

**Comment by emoose** [comment]
Do any of the C2C menu rankings save for you? Also does the log mention that "FixC2CRankings: apply successful" inside it?

**Comment by UserGit-2021** [comment]
> Do any of the C2C menu rankings save for you? Also does the log mention that "FixC2CRankings: apply successful" inside it?

Off-topic. Are you planning to fix Sega Rally Revo? For example, the ability to change key bindings?

**Comment by lance8765** [comment]
> Do any of the C2C menu rankings save for you? Also does the log mention that "FixC2CRankings: apply successful" inside it?

I remember seeing that "apply successful" message. Will try again later today.

**Comment by lance8765** [comment]
Ok, after reinstalling the game and using your Tweaks file with default settings, the Time Attack finally saves the rankings! I can't believe it took... what, 18 years?

Anyway, there are two problems for me now:

1) The game crashes when closing the game from title screen
2) The game gets stuck to the Sega logo at startup. I'm forced to disable Compatibility Mode on your executable.
