### ISSUE TITLE
Countdown Clock and Speedometer Textures Double Overlap

### ISSUE THREAD

**Issue by VirtualDavey** [emoose/OutRun2006Tweaks#41]
As you can see from the attached picture, the speedometer and the timer have a texture over a texture. A smaller version of the textures on top of a larger version of the textures. I've read about this issue a year ago on Reddit but found no solution.
![DSC00453](https://github.com/emoose/OutRun2006Tweaks/assets/68449802/f1b135b7-84f9-4187-b3fa-86e1a7ff979c)

**Comment by polybius22** [comment]
Seems like you need to go through FXT settings and turn the overlay it is generating off.

**Comment by VirtualDavey** [comment]
> Seems like you need to go through FXT settings and turn the overlay it is generating off.

Is that setting in Outrun2006Tweaks.ini? Can't seem to find it.

**Comment by polybius22** [comment]
Experimental HUD that has been successfully replaced lol
