### ISSUE TITLE
Patch breaks wheel support

### ISSUE THREAD

**Issue by CodingNutz** [emoose/OutRun2006Tweaks#44]
So I copy over the patched exe, DLL and ini, Launch the game and my Thrustmaster T500RS wheel no longer works. When I go into the controller menu, it thinks the wheel is a keyboard and lists 8 or so keys. If I switch to the keyboard, it’s lists all the x/y axis accelerator, beak options as if it thinks it’s a wheel. Altering any of them will not allow me to assign any wheel inputs. Hope you can fix this.

**Comment by emoose** [comment]
Could you try changing ControllerHotPlug in the INI to false? Maybe that's causing wheel not to get registered properly.
It might also be worth setting `VibrationMode = 0` & `ImpulseVibrationMode = 0`

`PreventDESTSaveCorruption` does also interact with the binding menu, maybe `PreventDESTSaveCorruption = false` could have some effect.

**Comment by CodingNutz** [comment]
Thanks for the quick feedback! Did the job. Just altered the vibration options to 0 and the ControllerHotPlug to false. Nice one! Keep up the good work!

**Comment by CodingNutz** [comment]
Thanks for the quick feedback! Did the job. Just altered the vibration options to 0 and the ControllerHotPlug to false. Nice one! Keep up the good work!

**Comment by chanunnaki** [comment]
Hey @CodingNutz, do you have FXT mod installing alongside _Tweaks_ or is it a fresh install?

**Comment by CodingNutz** [comment]
Hi, it was a fresh install with Tweaks.However, after poking around the internet, I switched over the FXT after I found out it fixes the massive dead zone on the wheel. Makes the game much more playable. I know it’s deprecated, and your tweaks are newer, but I couldn’t play the game with that quarter turn dead zone. Obviously I’d much prefer to use something newer that’s actively worked on. Could you maybe add some sort of fix for the wheel dead zone??Sent from my iPadOn 8 Jul 2024, at 10:07, chanunnaki ***@***.***> wrote:﻿
Hey @CodingNutz, do you have FXT mod installing alongside Tweaks or is it a fresh install?

**Comment by chanunnaki** [comment]
I see... I just set up my wheel yesterday, but only tried it with the Lindburgh/TeknoParrot version because I didn't want to futz around with FXT again and also Tweaks has no mention of wheel support at all, so I wasn't sure what the situation was regarding wheels.

Perhaps you could open another issue @CodingNutz regarding the dead zone!
