### ISSUE TITLE
[Feature Request] Sega sound at launch

### ISSUE THREAD

**Issue by ghost** [emoose/OutRun2006Tweaks#48]
Hello emoose, 

We have in the sound folder, a typical Sega sound : sega441.ogg. 

Surprisingly, I have never heard it in games, I would like to know if it is possible to add an option to make it work when launching the game at the same time as the presented by Sega screen appears. 

Thank you.

**Comment by chanunnaki** [comment]
+1 for this, I heard it when experimenting with the new SwitcherShuffleTracks setting.

**Comment by lance8765** [comment]
There are at least 3 unused audio files including that: https://github.com/emoose/OutRun2006Tweaks/issues/9#issuecomment-2184261474

**Comment by brad86m** [comment]
Does OR2 share engines with any other AM2 game ?
Left over asset that Sumo didn't delete, maybe.

**Comment by Dekaid0011** [comment]
I remember in an interview one of the devs said that they really wanted to have a button combo to play the classic sega sound on startup, but it was implemented too late and caused issues so the sound is in the files but unused.

**Comment by brad86m** [comment]
Yeah, you "Cheat Activated" when successfully inputting a code on Xbox OR2.

**Comment by lance8765** [comment]
So... is this considered "closed" because whoever opened the issue ragequit GitHub or there's really nothing that could be done? (will someone here ever read this message, anyway?)

**Comment by Tenome** [comment]
The opening video is a bk file, you could just edit the SFX in I think. I believe Howard (FXT) released some hacking tools.

**Comment by emoose** [comment]
Build at https://github.com/emoose/OutRun2006Tweaks/issues/39#issuecomment-2221028992 includes something for this, but sound has some popping/crackling at the start for me, I guess the sound code hasn't fully initialized yet or something by that time, could be why they didn't add it too :/

**Comment by Tenome** [comment]
It also crackles for me. Bummer!

**Comment by TheNomadSoulOmikron** [comment]
Just replace the Sega441.ogg file with this one and it works perfectly.

[sega441.zip](https://github.com/user-attachments/files/16227630/sega441.zip)

**Comment by lance8765** [comment]
> Just replace the Sega441.ogg file with this one and it works perfectly.
> 
> [sega441.zip](https://github.com/user-attachments/files/16227630/sega441.zip)

Where did you get it?

**Comment by TheNomadSoulOmikron** [comment]
> > Just replace the Sega441.ogg file with this one and it works perfectly.
> > [sega441.zip](https://github.com/user-attachments/files/16227630/sega441.zip)
> 
> Where did you get it?

I made it myself.

**Comment by Tenome** [comment]
Huh, I wonder why it works, because the original ogg file sounds fine when played by itself. Sometimes the solution is just that obvious lol.

**Comment by Tenome** [comment]
> Build at [#39 (comment)](https://github.com/emoose/OutRun2006Tweaks/issues/39#issuecomment-2221028992) includes something for this, but sound has some popping/crackling at the start for me, maybe the sound code hasn't fully initialized yet or something by that time, could be why they didn't add it too :/

Is this included in the action build you linked (https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465)? It doesn't play sega441.flac like it did with [your other DLL](https://github.com/emoose/OutRun2006Tweaks/issues/39#issuecomment-2221028992), which is the fix mentioned above.

**Comment by Tenome** [comment]
Whatever part of the shadow fix DLL that played the SEGA boot sound doesn't seem to be included in the newer DLLs, it'd be cool to see it restored.

**Comment by lance8765** [comment]
Are you telling me this is not yet on any stable release?

**Comment by lance8765** [comment]
> Whatever part of the shadow fix DLL that played the SEGA boot sound doesn't seem to be included in the newer DLLs, it'd be cool to see it restored.

Is it still MIA as of today? @emoose

**Comment by Tenome** [comment]
This is in Tweaks now, all is well.
