### ISSUE TITLE
Pegasus looping audio bug

### ISSUE THREAD

**Issue by emoose** [emoose/OutRun2006Tweaks#5]
Game sometimes has audio bug after the pegasus transition plays, where the horse stomping sound effect will keep looping for rest of the game.
Can kinda see it here: https://youtu.be/ZnPM6lJ0X4c?t=112, bit hard to make out with the music but the hooves effect keeps playing after they've gone.

Pegasus only appears after finishing 2 levels without any mistakes according to https://youtu.be/HnzYLCkfzK4?t=108

Not really sure where in the game code it gets setup, Outrun2SP symbols do have some functions related to "branch renditions", eg. `LoadBranchRenditionObject`, `GetBranchRenditionType`, `AreaIsBranchRenditionPlaying`.. sounds like it might be related to it.

There are also debug strings in C2C that seem to list all the different transitions, `BK Anim: HAWK` `BK Anim: PEGA` `BK Anim: PANZ`... unfortunately doesn't seem the code that uses these strings is present, not too sure what BK could stand for neither.

**Comment by lance8765** [comment]
It is unbelievable that you really fixed that bug. It wasn't even fixed in the FXT mod. Thank you so much!
