### ISSUE TITLE
xbox 360 controller does not work

### ISSUE THREAD

**Issue by kerryland** [emoose/OutRun2006Tweaks#50]
I installed "Repack by MagiPack (OutRun FXT mod included)" from [here](https://www.myabandonware.com/game/outrun-2006-coast-2-coast-cc3#download) and the game ran fine, including with my xbox360 controller, but when I installed these tweaks the controller was no longer operational -- except that it vibrated, even when driving with the keyboard!

**Comment by brad86m** [comment]
Conflictions with both mods.

Install vanilla OutRun from the disc and then this mod.

**Comment by kerryland** [comment]
I installed the vanilla version and found out that I needed to explicitly choose the controller from the "Options | Controller" page! I am an idiot.

There is still a bug in that the controller rumbles even if you are using the keyboard, which is a bit weird, but not a problem in the real world.

**Comment by lance8765** [comment]
Are you sure it works natively? Because i had to use Xidi, otherwise it's a mess to configure. See issue #10.

**Comment by kerryland** [comment]
I am not sure. I don't know how to be sure. I do know I can select a thing called something like "xbox360 controller" and the game seems to run.
