### ISSUE TITLE
Wrong texture for some fireworks sprites at the end of Metropolis

### ISSUE THREAD

**Issue by scheeseman486** [emoose/OutRun2006Tweaks#52]
![image](https://github.com/emoose/OutRun2006Tweaks/assets/125775274/577009d4-ad4a-41f7-989a-681e7359b441)
They seem to be using the texture for the road barriers that are on the track for some reason.

**Comment by lance8765** [comment]
A throwback to the ACIDDUDE cheat from Pandemonium 2, it made the graphics glitched on purpose, with wrong textures everywhere xD

**Comment by emoose** [comment]
This is a weird one, seems those sprites aren't drawn with the normal 2d/3d sprite functions, but looks like they're actually a 3D model which I guess draws them as billboard sprites somehow.

It's odd that fireworks seem to display fine up until game shows the GOAL screen, wonder if it's some memory issue where the fireworks get unloaded and then road marker loads in its place, or maybe the GOAL fireworks use some other model which included wrong texture for some reason.

Does anyone know if this happens on other C2C ports?

**Comment by Dekaid0011** [comment]
> Does anyone know if this happens on other C2C ports?

I know this also happens on C2C XBOX Port:
![firefox_aQskn2bm3E](https://github.com/emoose/OutRun2006Tweaks/assets/143886581/1caf8c87-beb5-49ab-9c1a-e17470179f99)

**Comment by Tenome** [comment]
That's a pretty funny glitch.

**Comment by lance8765** [comment]
Also happens on PS2, on the western editions at least. Too lazy to search for OR2SP videos, but i guess it's fixed there.

**Comment by Tenome** [comment]
Are there multiple firework textures? I can only find F785C0C9_128x128.dds, which is the red one.

**Comment by emoose** [comment]
Ah turns out it's code in DispStage that was drawing the fireworks, but using the wrong ID for them, should be fixed in https://github.com/emoose/OutRun2006Tweaks/commit/f1ed60b8494428f02488f52efb93372e5d36dc5f, luckily no need to edit the stage models 🐱.

Build at https://github.com/emoose/OutRun2006Tweaks/actions/runs/10903615900

**Comment by Tenome** [comment]
Ah, another classic simple mistake. I guess that's what happens when you have 6 months to port a game. Thanks for the fix.

**Comment by Dekaid0011** [comment]
With this fix enabled Fireworks now don't play at all on my end once in the ending animation:
![grafik](https://github.com/user-attachments/assets/c2a6f095-25f4-4de4-8d2d-226beaa88b89)

With the fix disabled 
![grafik](https://github.com/user-attachments/assets/906af2e3-1e85-4147-a4eb-a551fd1bc907)

**Comment by Tenome** [comment]
One step forward, one step back. I'll test it on my end too but it's probably the same.
