### ISSUE TITLE
[Feature Request] Restore missing/broken Horn button

### ISSUE THREAD

**Issue by ViperAcidZX** [emoose/OutRun2006Tweaks#53]
The F key or Button 3 on an XInput controller shown in the Controls configuration menu is supposed to sound a horn of your car, but they do absolutely nothing in this game. FXT Edition once had a "fix" by injecting a sound file (FXT Edition comes with a ``horn.wav`` files) but I am wondering if it's possible to fix the game's own car horn sound effects in the game through the Tweaks plugin?

**Comment by DonelBueno** [comment]
It is already implemented.

**Comment by ViperAcidZX** [comment]
Thank you guys, I see it in the recent commits so I'll go close this then.
