### ISSUE TITLE
Crashes on startup (Windows 7)

### ISSUE THREAD

**Issue by lance8765** [emoose/OutRun2006Tweaks#6]
Hi, this happens on both 0.2.2 and 0.2.3, and with both a legit copy of the game installed from an original DVD or versions found in the web.

Here's the error message:

![err1](https://github.com/emoose/OutRun2006Tweaks/assets/159916775/1b61a688-11ea-45db-adff-7f1dd71dcb27)
![err2](https://github.com/emoose/OutRun2006Tweaks/assets/159916775/5b7c62b4-6059-44fe-8a86-b82f82136534)
![err3](https://github.com/emoose/OutRun2006Tweaks/assets/159916775/f00ee49e-228e-4974-8469-2eecb980aebd)

Please note: the game is fully playable without the Tweaks files.

Also sorry if the images have Italian language.

**Comment by emoose** [comment]
Hm, it mentions MSVCP140 there, maybe newer VC redist is needed for the DLL, you can find latest at https://aka.ms/vs/17/release/vc_redist.x86.exe & https://aka.ms/vs/17/release/vc_redist.x64.exe.

If that doesn't help could you check if C:\Windows\Minidump\ folder has a OR2006C2C.dmp file inside and upload it somewhere if it does? (http://pixeldrain.com or http://we.tl should be able to host it)

**Comment by lance8765** [comment]
Already tried. Nothing has changed i'm afraid.

Also the Minidump folder is empty :(

Is this the same? It's from Users/Admin/AppData/Local/CrashDumps:

[OR2006C2C.EXE.5788.dmp](https://github.com/user-attachments/files/15775075/OR2006C2C.EXE.5788.dmp)

**Comment by emoose** [comment]
Yep looks like it, thanks.

Seems crash is while it's trying to setup log file, maybe can't write to file properly, can you try making a blank Outrun2006Tweaks.log next to game EXE and see if there's any difference?

The code it's erroring at is inside MSVCP140.dll though, inside function
> msvcp140.dll!mtx_do_lock(_Mtx_internal_imp_t * mtx, const xtime * target) Line 100	C++

If I search for errors related to that one post does mention it can happen if MSVCP140 is different version to what it built with: https://developercommunity.visualstudio.com/t/Visual-Studio-17100-Update-leads-to-Pr/10669759?sort=newest&topics=visual+studio+2019&WT.mc_id=WD-MVP-5003763

For me MSVCP140.dll shows as version 14.40.33810, maybe check if yours is the same

**Comment by lance8765** [comment]
The blank .log file is already created when trying to launch the game for the first time... O_o"

**Comment by lance8765** [comment]
Okay, installing the x86 redist fixed the crashes on startup... but it looks a little "unstable" to me for now... needs more testing.

**Comment by DonelBueno** [comment]
Did you change the '.exe" compatibility mode? If so, try disabling it, that is, run with no compatibility changes applied.

**Comment by lance8765** [comment]
> Did you change the '.exe" compatibility mode? If so, try disabling it, that is, run with no compatibility changes applied.

That was one of the first things i tried, enabling compatibility mode...

**Comment by lance8765** [comment]
Ok, after dealing with Issue #4 and fixing the crashes at startup in this one, i have two new problems:

1. The executable crashes when closing the game from title screen
2. The game gets stuck to the Sega logo at startup. I'm forced to disable Compatibility Mode on your executable to solve the issue. It it going to make any difference? Also it was working fine with that setting until yesterday, when i decided to fully update my operating system after a couple of years without doing it..

**Comment by emoose** [comment]
Ah thanks for letting me know about that crash issue, seems MS actually hide that "app stopped responded" dialog box since Win10 so hasn't actually seen that on my end - re-enabling the dialog like https://stackoverflow.com/questions/51814677/how-to-enable-program-has-stopped-working-dialog mentions does show it for me now though, will look into a fix for it shortly.

Should probably be fine to disable the compatibility mode options, been playing without any compatibility enabled and all seems fine on Win11.

**Comment by lance8765** [comment]
This is good to know. Thank you! Will wait for updates.

I reported that thing about Compatibility Mode because apparently it was already set to "Windows 98 / Windows Me" by default.

**Comment by emoose** [comment]
That compat setting might have been carried over from your original EXE, AFAIK windows saves it for the EXE path, so if you unzip the tweaks ZIP to some other folder it should have it cleared.

Posted 0.2.4 which should hopefully resolve the crash on exit: https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.2.4

If you notice any more issues or have other suggestions please let me know!

**Comment by lance8765** [comment]
Oh, really? So even if i uninstalled/reinstalled the game several times, the setting is kept? Shame on me :(

Thanks for the update, will test it as soon as possible.

**Comment by lance8765** [comment]
Ok, it closes without crashing...

AAAAAND... i consider it solved. Thank you very much, again.
