### ISSUE TITLE
Freeze on Gamestart ( at logos)

### ISSUE THREAD

**Issue by GameGear84** [emoose/OutRun2006Tweaks#62]
Game crahses at start, sometimes it dont crash at start and  i can play, finish a race but if the loading screen appers it freeze up again.
The gamefile are ok ( i can play with ethe same gamefiles on my intel nuc flawlessly ) but its not my main System here are the Specs of my main System

i7 13th gen
RTX 4060Ti 16gb
32GB Ram
Windows 10 64bit

**Comment by emoose** [comment]
Do you know which ver of tweaks you used? Might be able to find the version from the zip you downloaded

Maybe try the latest at https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465, it fixed some other hanging issues which might help

**Comment by richardk2009** [comment]
I have this issue and can confirm it occurred even before OutRun2006Tweaks. It occurs to me if I run the original or any tweaked version of the exe. So issue is likely more with the game itself.

My machine is:
i5 12600k
RTX 3080ti
16GB Ram
Windows 10 64-bit

So a few commonalities with OP build, (Intel, Nvidia, etc).

**Comment by GameGear84** [comment]
> Do you know which ver of tweaks you used? Might be able to find the version from the filename of the zip you downloaded
> 
> Maybe try the latest at https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465, it fixed some other hanging issues which might help

Hi there. Yes I  tried the latest releases and it’s the same ( and it’s right that it happens even without the tweaks). So maybe a multicore or NVIDIA gpu Problem ? I hope someone find a fix for that

**Comment by richardk2009** [comment]
> > Do you know which ver of tweaks you used? Might be able to find the version from the filename of the zip you downloaded
> > Maybe try the latest at https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465, it fixed some other hanging issues which might help
> 
> Hi there. Yes I tried the latest releases and it’s the same ( and it’s right that it happens even without the tweaks). So maybe a multicore or NVIDIA gpu Problem ? I hope someone find a fix for that

Issue definitely relates to cores. Or number of cores. I have the exact issue and this is how to temporarily solve.

Keep starting the game until it gets to main menu (may take multiple attempts, sometimes 5-10 attempts). When in main menu, alt-tab out, open task manager, look for OR2006 exe in the details tab. Right click and set affinity. Untick all cores but 1 (leave CPU 0 ticked if unsure).

You'll find the game will no longer crash after races. I tried this and confirmed. I played 10 races without crashing.

So at least its playable now, just need to attempt start multiple times to get past logos.

I tried setting affinity with a shortcut or Process Lasso but neither seemed to catch the issue in time, so manually setting affinity once in main menu was the best success I had.

If you have a slower CPU, setting to 1 core may reduce performance, but it was fine on my i5-12600k and I think OP had a good CPU too.

**Comment by GameGear84** [comment]
> > > Do you know which ver of tweaks you used? Might be able to find the version from the filename of the zip you downloaded
> > > Maybe try the latest at https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465, it fixed some other hanging issues which might help
> > 
> > 
> > Hi there. Yes I tried the latest releases and it’s the same ( and it’s right that it happens even without the tweaks). So maybe a multicore or NVIDIA gpu Problem ? I hope someone find a fix for that
> 
> Issue definitely relates to cores. Or number of cores. I have the exact issue and this is how to temporarily solve.
> 
> Keep starting the game until it gets to main menu (may take multiple attempts, sometimes 5-10 attempts). When in main menu, alt-tab out, open task manager, look for OR2006 exe in the details tab. Right click and set affinity. Untick all cores but 1 (leave CPU 0 ticked if unsure).
> 
> You'll find the game will no longer crash after races. I tried this and confirmed. I played 10 races without crashing.
> 
> So at least its playable now, just need to attempt start multiple times to get past logos.
> 
> I tried setting affinity with a shortcut or Process Lasso but neither seemed to catch the issue in time, so manually setting affinity once in main menu was the best success I had.
> 
> If you have a slower CPU, setting to 1 core may reduce performance, but it was fine on my i5-12600k and I think OP had a good CPU too.

thanky for that it worked out for me.

**Comment by emoose** [comment]
Hm, will look into adding something to force it to 1 core in next release, it's odd though since game only really uses 3 threads for things, on my 12900 (16c/24t) I've only really had load screen freeze maybe 2 times out of 1000+ loads, not sure why it seems worse on other systems.

**Comment by richardk2009** [comment]
@emoose - I wonder if it relates to the efficiency cores. Both @GameGear84  and myself have CPUs with E-cores. Maybe if 1 of the threads ends up on an E-core. it gets out of time with the others.

**Comment by emoose** [comment]
Just added `SingleCoreAffinity` setting that should force it to single core, could you try the artifact build at https://github.com/emoose/OutRun2006Tweaks/actions/runs/9983476291 and see if it's any better? Should be up there in a few mins

Make sure to enable `SingleCoreAffinity` in the INI though since it's not enabled by default

**Comment by GameGear84** [comment]
> Just added `SingleCoreAffinity` setting that should force it to single core, could you try the artifact build at https://github.com/emoose/OutRun2006Tweaks/actions/runs/9983476291 and see if it's any better? Should be up there in a few mins
> 
> Make sure to enable `SingleCoreAffinity` in the INI though since it's not enabled by default

hi emmose, thank you very much , i tested it a bit , it seems to be working so far :-)
