### ISSUE TITLE
Car shadow "fix" crashes game at launch

### ISSUE THREAD

**Issue by Outrunner24** [emoose/OutRun2006Tweaks#66]
The file posted [here](https://github.com/emoose/OutRun2006Tweaks/issues/39#issuecomment-2221028992) doesn't work for me, if I replace the dinput8.dll the game won't start anymore. Win10/AMD APU on the latest release.

**Comment by emoose** [comment]
Does the latest action build from https://github.com/emoose/OutRun2006Tweaks/actions work? That should include the car shadow fix now
The earlier build did include a kinda janky attempt at adding the sega chant back, maybe that stopped it launching for you

**Comment by Outrunner24** [comment]
> Does the latest action build from https://github.com/emoose/OutRun2006Tweaks/actions work? 

Sorry but I don't know what I have to do on that page. I downloaded an .EXE but it does nothing new (no car shadow).

**Comment by emoose** [comment]
The file at https://github.com/emoose/OutRun2006Tweaks/actions/runs/9902921831/artifacts/1693921743 should include a dll/ini, should include the car shadow fix

**Comment by Outrunner24** [comment]
THANKYOU! Everything's fine now :-)

![shadow](https://github.com/user-attachments/assets/b6c10f83-3cc7-441d-a2ed-1acd65103b60)

The perfect opacity for me is 1.5 - Shadow's a bit off if you look at the tires but I guess it's just how the car models were made.
