### ISSUE TITLE
[Feature Request]: Replace "Not Signed In" on main menu with a working OutRun Miles counter like the Japanese PS2 version

### ISSUE THREAD

**Issue by lance8765** [emoose/OutRun2006Tweaks#70]
### Describe the feature you'd like to see added

As seen here and previously mentioned on issue #13: https://www.youtube.com/watch?v=9G6grKzHhDI

**Comment by emoose** [comment]
Added in 7f12dfab61c1eb8a0898ff23669c5c22b9d68885 😸 
That changes it to show the miles next to the text, eg. "Not Signed In - OutRun Miles: 12345"

It could be worth adding this for the signed in text as well, will need to check if there's enough room for it there.

**Comment by lance8765** [comment]
Really? Thank you so much! I'm finally closing this.
