### ISSUE TITLE
[Bug]: CD Switcher causing consistent crashes when transitioning to the next song (not skip).

### ISSUE THREAD

**Issue by Tenome** [emoose/OutRun2006Tweaks#71]
### Tweaks version

v0.4.1 with the loading time fix that you posted in the other issue thread

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

I added some songs to the switcher, but I've been getting consistent crashes. It appears that if I let it transition to the next song rather than skipping, it causes a crash.  I tested this multiple times, and it's consistent.

This does not seem to occur with the base game ogg files. If I had to guess, it's because normally the ogg files are set to loop by the game, but since that doesn't exist for the FLACs (or oggs that you add that don't replace any of the base filenames, since they don't have anything that tells them to loop), it doesn't know what to do when it reaches the end of the song and crashes.

Does the CD Switcher actually have a function to transition to the next song, or does it just play it? As a stopgap measure, perhaps a function that automatically skips the song when it reaches the last second could be implemented until this is hopefully fixes. Or to imitate the original game, and tell any CD Switcher songs to loop endlessly?

I'm surprised that no one else seems to have brought this up before. I guess everyone else is either lucky, not using the CDS, or has just been skipping songs manually the entire time.
[OutRun2006Tweaks.log](https://github.com/user-attachments/files/16232713/OutRun2006Tweaks.log)

**Comment by areyabuzzin** [comment]
I just want to add that I have the same issue too.

**Comment by emoose** [comment]
Does the latest action build help at all? There was a hanging bug with flacs which it fixed: https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465

**Comment by areyabuzzin** [comment]
> Does the latest action build help at all? There was a hanging bug with flacs which it fixed: https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465

I used that build and the consistent crashes still remain. 
I noticed it crashes more after a race is completed, like when you're suppose to start the next race (on coast to coast mode). 

Not sure if it's cause I'm trying to skip tracks too fast (to get to the track I want) or if I maybe have too many additional tracks (I've added 112 tracks).

**Comment by Tenome** [comment]
> Does the latest action build help at all? There was a hanging bug with flacs which it fixed: https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465

This fixed it for me, but I'll leave the issue up since areyabuzzin reported an issue. I let the first song loop normally while idling at the start, and then played Outrun continuous mode as normal. I also played Coast to Coast mode, including letting it idle at the "Next Race" screen to see if that caused issues when looping. No problems with any of those.

**Comment by areyabuzzin** [comment]
I think I can add to this strange bug. 
If you skip tracks it's fine but if you reverse skip tracks, it always seems to crash to desktop (I do have a massive tracks list though).

**Comment by areyabuzzin** [comment]
> > Does the latest action build help at all? There was a hanging bug with flacs which it fixed: https://github.com/emoose/OutRun2006Tweaks/actions/runs/9921117465
> 
> I used that build and the consistent crashes still remain. I noticed it crashes more after a race is completed, like when you're suppose to start the next race (on coast to coast mode).
> 
> Not sure if it's cause I'm trying to skip tracks too fast (to get to the track I want) or if I maybe have too many additional tracks (I've added 112 tracks).

I think I can add to this strange bug. 
If you skip tracks it's fine but if you reverse skip tracks, it always seems to crash to desktop (I do have a massive tracks list though).

**Comment by Tenome** [comment]
Do your tracks have any special characters or non-English filenames? I had a couple that caused the game to crash until I renamed them.

**Comment by areyabuzzin** [comment]
> Do your tracks have any special characters or non-English filenames? I had a couple that caused the game to crash until I renamed them.

I scrubbed out all weird characters and even removed all traces within the metadata. 
It still seems fine when I skip tracks normally but it still crashes to desktop when I skip tracks backwards.

**Comment by emoose** [comment]
>I noticed it crashes more after a race is completed, like when you're suppose to start the next race (on coast to coast mode).

Ah I think the issue was game was still looking the current track number up in the original tracklist when you start a race, that list only has 37 tracks or so, so if you were playing track 50 and then chose "next race" it'd read an invalid value from the list.

Just pushed something which should force it to read from our tracklist now, could you check if the artifact build from https://github.com/emoose/OutRun2006Tweaks/actions/runs/9983282061 helps?

Haven't been able to repro the previous track crash yet, maybe this will help though.

**Comment by areyabuzzin** [comment]
Hey @emoose 
I've just tried this for an hour and it all works perfectly for me now.
Thanks for all hard work! 👍

> > I noticed it crashes more after a race is completed, like when you're suppose to start the next race (on coast to coast mode).
> 
> Ah think the issue was game was still looking the current track number up in the original tracklist when you start a race, that list only has 37 tracks or so, so if you were playing track 50 and then chose "next race" it'd read some invalid value from it.
> 
> Just pushed something which should force it to always read from our tracklist now, could you check if the artifact build from https://github.com/emoose/OutRun2006Tweaks/actions/runs/9983282061 helps?
> 
> Haven't been able to repro the previous track crash yet, maybe this will help though.
