### ISSUE TITLE
[Feature Request]: Can the time attack-exclusive level transitions be flagged for Outrun mode, etc. too?

### ISSUE THREAD

**Issue by Tenome** [emoose/OutRun2006Tweaks#73]
### Describe the feature you'd like to see added

There are a handful of hidden level transition effects that are exclusive to time attack mode, I believe. A hang glider, a jet, a UFO, and I think Panzer Dragoon (this one does show up in regular Outrun modes I think, it's just very rare). There might be one or two that I don't remember. Since most people just play arcade or Outrun, they'll never see these. Would it be possible to flag them for appearing outside of time attack too?

**Comment by Outrunner24** [comment]
I don't think they're exclusive to Time Attack, I've seen the hang glider a few times in arcade mode. They're probably glitchy (like the pegasus sounds were) and don't always show up.

**Comment by lance8765** [comment]
This is the first time i hear that certain transitions are exclusive to certain modes. I think they depend on player's performance though.

**Comment by Dekaid0011** [comment]
definetly haven't seen the hot air balloons, stunt planes, afterburner or UFO animations outside of time trial, those are specific to timed performance I believe

**Comment by emoose** [comment]
Looking at code for it, seems each gamemode uses a set of 7 different transitions (out of the 14 total), so one mode might show balloons if you have a crash, while another mode might show the wing glider guy, etc.

Not really sure how we could extend that since it's just picking a set to use based on the game mode, only idea I've had is maybe adding a setting to randomize which set it'll use when it picks it, so there could be a chance it'd pick the transition from a different set instead.

**Comment by Tenome** [comment]
A working randomize setting would be perfect.

**Comment by emoose** [comment]
Here's a build which should randomize the sets, _think_ it's working since I did get the UFO anim with this for the first time, I guess that probably replaces the pegasus in some mode.

[OutrunTweaks-RandomHighwayAnimSets.zip](https://github.com/user-attachments/files/16276325/OutrunTweaks-RandomHighwayAnimSets.zip)

**Comment by Tenome** [comment]
> Here's a build which should randomize the sets, _think_ it's working since I did get the UFO anim with this for the first time, I guess that probably replaces the pegasus in some mode.
> 
> [OutrunTweaks-RandomHighwayAnimSets.zip](https://github.com/user-attachments/files/16276325/OutrunTweaks-RandomHighwayAnimSets.zip)
> 
> (E: should be in latest action build now too, will need to enable `RandomHighwayAnimSets` in INI for that though)

I played a couple 15 matches, and while it is randomized, it seems to use the same seed for all races. I didn't record it, so I can't be 100%, but I'm pretty confident I saw the same transitions order when I finished one Outrun 15 and started the other (easy to tell because I got hot air balloons twice in a row). Or is that how the base game works, by generating the order when it boots?

**Comment by emoose** [comment]
It should be randomizing the set just before it starts the anim, did just notice that some of the sets are actually duplicated though, one of them is actually duplicated 8 times, so would have had a much higher chance of that getting used...

A list of the sets for reference:
```
00: BRA_SHIP,   BRA_BALL,   BRA_HANG, BRA_JETL, BRA_PROP, BRA_FIGH, BRA_UFOO
01: BRA_BIRD_M, BRA_BIRD_G, BRA_HAWK, BRA_FRAM, BRA_WAIB, BRA_PEGA, BRA_PANZ
02: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
03: BRA_BIRD_G, BRA_JETL,   BRA_HAWK, BRA_WAIB, BRA_HANG, BRA_UFOO, BRA_FRAM
04: BRA_BIRD_G, BRA_JETL,   BRA_HAWK, BRA_WAIB, BRA_HANG, BRA_UFOO, BRA_FRAM
05: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
06: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
07: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
08: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
09: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
10: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
11: BRA_SHIP,   BRA_BALL,   BRA_JETL, BRA_HANG, BRA_UFOO, BRA_PROP, BRA_FIGH
12: BRA_BALL,   BRA_BALL,   BRA_BALL, BRA_BALL, BRA_BALL, BRA_BALL, BRA_BALL
13: BRA_BIRD_M, BRA_BIRD_G, BRA_HAWK, BRA_FRAM, BRA_WAIB, BRA_PEGA, BRA_PANZ
14: BRA_SHIP,   BRA_BALL,   BRA_HANG, BRA_JETL, BRA_PROP, BRA_FIGH, BRA_UFOO
```
and the duplicates:
```
0/14
1/13
2/5/6/7/8/9/10/11
3/4
```

Seems the main unique ones are just 0/1/2/3 (and 12 which only allows balloon anim for some reason?), guess I should just change it so it'll pick from those first 4 instead.

**Comment by Tenome** [comment]
I wonder if there's any documentation on the requirements to trigger certain animations. Jumbo jet seems to be if you're under your best time, and the jet if you beat it. The dragon seems to be if you get a perfect lap (no collisions, always stay on the road), maybe another if you get two perfect laps (Pegasus)? According to this video, in Online Arcade this triggers Panzer Dragoon instead (https://www.youtube.com/watch?v=GBtVUvzrtdw). So maybe I misremembered about Panzer Dragoon since it doesn't look like it's in Coast 2 Coast. I got two blimps but I don't know what caused that. Maybe it's just beating certain times in general.

**Comment by emoose** [comment]
This vid does go through a couple of them in C2C: https://www.youtube.com/watch?v=HnzYLCkfzK4

They mentioned panzer dragoon after perfect lap & pegasus after 2 laps like you guessed, the dragon they show looks different to the online arcade one though (afaik it does get called PANZ in the code, maybe they just improved the model in online arcade, or maybe SDX which came after C2C?)

Blimp is apparently after a hard crash, maybe balloons is for smaller hits?

**Comment by Tenome** [comment]
Oh, that dragon is supposed to be from Panzer? No wonder I didn't recognize it, the model looks different. I think Lagi does have a green form or glow at some point, but I haven't played the game in years. Now I wonder if we could replace the model...

**Comment by Dekaid0011** [comment]
> They mentioned panzer dragoon after perfect lap & pegasus after 2 laps like you guessed, the dragon they show looks different to the online arcade one though (afaik it does get called PANZ in the code, maybe they just improved the model in online arcade, or maybe SDX which came after C2C?)

Just wanna mention there is 2 dragon animations, though idk myself how to get the grey/silver one, also makes a higher pitch scream.

Also the fighter jet and ufo aren't fully about beating your previous best time it seems, I frequently get splits within the same tenth or only one off and still get the afterburner animation, I also remember getting UFO a few times without setting a personal best stage time, but I'm not completely sure on that.

**Comment by Tenome** [comment]
Managed to get this Orta one, don't think I've gotten it before.

![image](https://github.com/user-attachments/assets/bcb46584-2ff6-4010-8985-ccce366328e4)

**Comment by Dekaid0011** [comment]
> Managed to get this Orta one, don't think I've gotten it before.

Also on the second junction. I assume it's imperfect first stage and perfect second stage, atleast that's how I got it once aswell.
