### ISSUE TITLE
[Bug]: Cannot Add Further Custom Tracks from Track 141 Onwards

### ISSUE THREAD

**Issue by areyabuzzin** [emoose/OutRun2006Tweaks#84]
### Tweaks version

outrun2006tweaks-e7016a80028b9f907ee273d87f0b909ed19bf82c

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

I'm unable to add further custom tracks from track 141 onwards.
Any tracks from track 141 upwards that I've created default to the standard Outrun Splash Wave soundtrack

[OutRun2006Tweaks.log](https://github.com/user-attachments/files/16339547/OutRun2006Tweaks.log)

**Comment by lance8765** [comment]
This is weird, the 20th Anniversary Box has more than 200 tracks and all work well... are you sure you didn't miss something? Like the file format for the audio files?

**Comment by areyabuzzin** [comment]
I'm using .ogg files. 
I tried again with a different track and I still get the same issue on track 141 onwards.

**Comment by Tenome** [comment]
Attach the log file like the template says, it prints a statement for every song it loads. Are the songs not even being loaded in the log file, or are they being loaded but not functioning for some reason?

**Comment by areyabuzzin** [comment]
[OutRun2006Tweaks.log](https://github.com/user-attachments/files/16339501/OutRun2006Tweaks.log)

**Comment by emoose** [comment]
Odd that it stops loading at 141 but then continues to load the Last_Wave.ogg / SEGA441.ogg / etc files after them, maybe the tracks after 141 start with a comment `#` / `;` symbol? Could you post your INI as well?

**Comment by areyabuzzin** [comment]
# OutRun2006Tweaks - https://github.com/emoose/OutRun2006Tweaks

[Performance]
# Set to 0 to disable this framelimiter if you want to use an external one instead.
#  (with FramerateUnlockExperimental enabled this can be increased above 60FPS without affecting game speed)
FramerateLimit = 165

# 0 = efficient mode
# 1 = accurate mode
# Default 0 should work fine for most people, but if you have issues it might be worth trying the accurate mode.
FramerateLimitMode = 0

# Unlimits framerate during load screens to help reduce load times.
#  0 = disable
#  1 = unlimit framerate during load screens
#  2 = unlimit framerate & disable vsync during load screens (fastest load times but may cause screen flash)
#  3 = processes file loads inside the framelimiter, reducing the time taken by both load screens & in-game stage loading
FramerateFastLoad = 3

# Should usually be fine to leave this enabled, but if you have frame issues feel free to disable this here.
FramerateUnlockExperimental = true

# Set to 0 to disable VSync, 1 for normal v-sync, or 2 for half-refresh-rate vsync
VSync = 0

# A few modern multi-core CPUs may have crashing/freezing issues on game launch or load screens
# If you encounter these often you can try enabling SingleCoreAffinity to force the game to a single core
# This may have a small hit on performance/load times if enabled
SingleCoreAffinity = false

[Graphics]
# Adjusts the UI scaling applied by the game
#  0 = game default, stretches to screen ratio
#  1 = fixed UI scaling without stretching, based on Outrun Online Arcade
#  2 = 4:3 UI centered to middle of screen
# Outrun Online Arcade scaling required many manual code changes, please let me know if you notice anything broken!
UIScalingMode = 1

# Adds 4:3 letterboxing to game menus, to address some graphical issues outside of the menus 4:3 display
#  0 = disable all letterboxing
#  1 = letterbox menus only, disabled when in-game
#  2 = always letterbox (only recommended with UIScalingMode = 2)
# NOTE: this letterboxing is only used when UIScalingMode is set to 1 or above
UILetterboxing = 1

# 1 - 16, 0 to leave it at games default.
AnisotropicFiltering = 16

# Resolution used for car reflections, games default is 128x128, 2048x2048 seems a reasonable improvement
ReflectionResolution = 2048

# Allows game to enable 4x transparency supersampling, heavily reducing aliasing on things like barriers or cloth around the track edge.
#  For best results use this with "DX/ANTIALIASING = 2" inside outrun2006.ini
TransparencySupersampling = true

# Fixes certain stage objects disappearing before they reach edge of screen, when playing at non-4:3 aspect ratio.
ScreenEdgeCullFix = true

# Disables LODs on vehicles, reducing the ugly pop-in they have.
DisableVehicleLODs = true

# Disables culling of certain stage objects, so most distant objects won't obviously pop in to view.
DisableStageCulling = true

# Fixes Z-Buffer precision issues, greatly reducing z-fighting and distant object drawing issues (eg. signs/buildings will have much less pop-in)
FixZBufferPrecision = true

# Restores the player car base shadow that was included in other C2C ports
#  The shadows opacity can be customized, opacity = 1.0 can help mask some issues with the stencil shadowing
#  Xbox C2C seems to use opacity 0.5, but that makes it very transparent on PC, likely not ideal
CarBaseShadowOpacity = 1.0

# Allows textures to be replaced if a matching texture exists inside textures\load\ folder
#  Textures must be named as [hash]_[width]x[height].dds, where hash/width/height comes from the original texture to be replaced
#  They can also be kept in seperate subfolders for the texture package the original texture belongs to, or just kept inside the base texture\load\ folder
#  You can find the correct filename/texture package name by enabling TextureDump below
SceneTextureReplacement = true
UITextureReplacement = true

# Dumps out textures into textures\dump\ folder as the game loads them in (if a replacement texture isn't loaded)
#  Textures will be dumped into separate subfolders for the texture package each texture belongs to
SceneTextureDump = false
UITextureDump = false

[Audio]
# Allows using horn outside of the "beep the horn!" girlfriend missions
AllowHorn = true

# Allows game to load in uncompressed WAV files instead of compressed OGG
#  WAV files must have the same filename as the original OGG, eg. "Sound\14_Rush_a_Difficulty_1989.wav"
AllowUncompressedBGM = true

# Adds support for loading FLAC audio files
#  FLAC files must have the same filename as the original OGG, eg. "Sound\14_Rush_a_Difficulty_1989.flac"
#  (requires AllowUncompressedBGM to be enabled to work)
AllowFLAC = true

[CDSwitcher]
# Installs an aftermarket CD switcher onto each of your cars, switcher can be used to change music tracks during a race.
#  Track can be changed either using Z and X keyboard keys, or Back / RS+Back gamepad buttons
#  (gamepad buttons can be rebound below)
#
# The tracks played by the CDSwitcher can be customized in the CDTracks section at the end of this file
# Custom tracks can also be added there for CDSwitcher to load in
# (AllowUncompressedBGM must be enabled above for CDSwitcher to function correctly)
SwitcherEnable = true

# Whether to display track title after switching
SwitcherDisplayTitle = true

# Allows customizing the track title font (certain fonts may be missing glyphs such as square brackets)
# Valid fonts are 0 to 9
# SwitcherTitlePosition is where the track title is drawn on screen based on games original 640x480 screen dimensions
SwitcherTitleFont = 2
SwitcherTitleFontSizeX = 0.3
SwitcherTitleFontSizeY = 0.5
SwitcherTitlePositionX = 375
SwitcherTitlePositionY = 450

# Shuffles the tracks defined in CDTracks section on game launch
SwitcherShuffleTracks = false

# Gamepad button combinations to bind to the CD switcher
# Combinations of buttons can be specified, eg. LB+Back to require both LeftBumper and Back button to be pressed
# Any of the following can be specified in a combination:
#   Buttons: A, B, X, Y, LB, RB, LS, RS, LT, RT, Start, Back
#   Sticks: LS-Up, LS-Down, LS-Left, LS-Right, RS-Up, RS-Down, RS-Left, RS-Right
#   Dpad: Up, Down, Left, Right
TrackNext = A
TrackPrevious = B

[Vibration]
# Enable/disable the xbox vibration code, or customise it
#  0 = disable
#  1 = enable xbox vibration code
#  2 = ^ with L/R motors swapped
#  3 = ^ with L/R motors merged together
VibrationMode = 0

# XInput device to send vibration to, default should work fine in most cases, but if you don't notice any vibration you can try increasing this here
VibrationControllerId = 0

# VibrationStrength range is 0 to 10
VibrationStrength = 7

# Enable/disable Xbox Series impulse trigger vibration, or customise it
# (VibrationMode must be enabled above for this to work)
#  0 = disable
#  1 = enable impulse triggers
#  2 = ^ with L/R motors swapped (recommended for impulse triggers)
#  3 = ^ with L/R motors merged together
ImpulseVibrationMode = 2

# Multipliers of the trigger vibration, the normal controller motor vibration is multiplied by these to set trigger value
ImpulseVibrationLeftMultiplier = 0.20
ImpulseVibrationRightMultiplier = 0.20

[Window]
# Forces windowed mode to become borderless. (requires "DX/WINDOWED = 1" inside outrun2006.ini)
WindowedBorderless = true

# Only applied if WindowedBorderless is set to true.
WindowPositionX = 0
WindowPositionY = 0

# Hides mouse cursor while game window is active.
WindowedHideMouseCursor = true

# Disables DPI scaling on game window, can help fix issues when screen DPI is set above 100%
DisableDPIScaling = true

# If the outrun2006.ini file doesn't exist, changes games default 640x480 resolution to primary display resolution instead
#  Otherwise the resolution from outrun2006.ini (or Config.exe tool) will be used
AutoDetectResolution = true

[Misc]
# Skips the beginning intro logos, saving a couple seconds from startup time. (game will still show a white screen for 5-10 seconds while data loads in)
#  Can also be enabled via -SkipIntros launch parameter.
SkipIntroLogos = false

# Disables the countdown timer, may be useful for modders, or those who just want to take a leisurely drive.
#  Can also be enabled via -OuttaTime launch parameter.
DisableCountdownTimer = false

# Clarissa in O2SP arcade mode uses a different model in non-JP versions, this allows restoring the original JP model
RestoreJPClarissa = true

# Allows game to pick highway animations from other game modes
# Normally each game mode has it's own hardcoded set of highway anims it can play, eg. one mode might show balloons after a crash, while a different one might show wing glider guy
# With this enabled the game can pick from other modes instead of just the one currently being played
# (this doesn't completely randomize which animation to play - anims will still have conditions that have to be met)
RandomHighwayAnimSets = false

[Bugfixes]
# Fixes looping clop sound effect remaining active through the session.
FixPegasusClopping = true

# Fixes C2C scoreboard rankings not updating due to incomplete anti-piracy checks.
FixC2CRankings = true

# Prevents the "DEST" save corruption caused by remapping controls with many devices connected.
#  (if you got hit by this bug, you can restore name/model by replacing first 0xB0 bytes in your corrupted License.dat file with the contents of a different one)
PreventDESTSaveCorruption = true

# Game tries to load in lens flare data from common/, but the game files have it inside media/, causing lens flare not to be drawn.
#  If lens flare is still present inside media/ then this will just patch game to load it from there instead.
FixLensFlarePath = true

# Fixes certain effects in the game like backfiring which tried to check if pedal/trigger is being fully pressed
#  (vanilla DirectInput wouldn't return a high enough value to register, this just nudges it toward the value being checked)
FixFullPedalChecks = true

# Hides text related to the now-defunct online service
HideOnlineSigninText = true

# Allows game to detect newly plugged in devices, rather than needing a restart
ControllerHotPlug = true

[CDTracks]
# Defines tracks and the order they can be selected via the CDSwitcher above
#  Tracks can be added/removed as desired, along with any custom WAV/OGG files
#  Format of each line should be
#  [track file path] = [track display name]
#
#  Full file paths can also be used, without requiring quotation marks, eg
#    C:\My Music\Outrun 2\Splash Wave Remix.wav = Splash Wave Remix
#
#  (note that this only affects tracks played through CDSwitcher, this currently doesn't affect the track selection menu in-game)

01_Splash_wave.ogg = Splash Wave
02_Magical_Sound_Shower.ogg = Magical Sound Shower
03_Passing_Breeze.ogg = Passing Breeze
04_Risky_Ride.ogg = Risky Ride
05_Shiny_World.ogg = Shiny World
06_Night_Flight.ogg = Night Flight
07_Life_was_a_Bore.ogg = Life was a Bore
08_Radiation.ogg = Radiation
09_Night_Bird.ogg = Night Bird
10_Splash_wave_1986.ogg = Splash Wave (1986)
11_Magical_Sound_Shower_1986.ogg = Magical Sound Shower (1986)
12_Passing_Breeze_1986.ogg = Passing Breeze (1986)
13_Shake_the_Street_1989.ogg = Shake the Street (1989)
14_Rush_a_Difficulty_1989.ogg = Rush a Difficulty (1989)
15_Who_are_You_1989.ogg = Who are You (1989)
16_Keep_Your_Heart_1989.ogg = Keep Your Heart (1989)
17_Splash_Wave_EuroMix.ogg = Splash Wave (EuroMix)
18_Magical_Sound_Shower_EuroMix.ogg = Magical Sound Shower (EuroMix)
19_Passing_Breeze_EuroMix.ogg = Passing Breeze (EuroMix)
20_Risky_Ride_Guitar_Mix.ogg = Risky Ride (Guitar Mix)
21_Shake_the_Street_ARRANGED.ogg = Shake the Street (ARRANGED)
22_Who_are_you_ARRANGED.ogg = Who are You (ARRANGED)
23_Rush_a_difficulty_ARRANGED.ogg = Rush a Difficulty (ARRANGED)
24_Keep_your_Heart_ ARRANGED.ogg = Keep your Heart (ARRANGED)
25_Shiny_World_prototype.ogg = Shiny World (Prototype)
26_Night_Flight_prototype.ogg = Night Flight (Prototype)
27_Life_was_a_Bore_Instrumental.ogg = Life was a Bore (Instrumental)
28_Night_Flight_Instrumental.ogg = Night Flight (Instrumental)
29_ABCD.ogg = ABCD
30_Control_Your_Music.ogg = Control Your Music
31_We_Close_Our_Eyes.ogg = We Close Our Eyes
32_VISTA.ogg = VISTA
33_Beyond_The_Horizon.ogg = Beyond The Horizon
34_V.ogg = V 
35_TI_Lv6.ogg = TI Lv6
36_Butterfly_Delaction_Remix.ogg = Butterfly (Delaction Remix)
37_C_Note.ogg = C Note
38_Together_In_Electric_Dreams.ogg = Together In Electric Dreams
39_Control_Your_Music.ogg = Control Your Music
40_Criticize.ogg = Criticize
41_Dhalsim_TEKINA_Remix.ogg = Dhalsim (TEKINA Remix)
42_Dibby-Dibby-Sound-feat-Ms-Dynamite.ogg = Dibby Dibby Soundfeat Ms Dynamite
43_DRAGOSTEA_DIN_TEI.ogg = DRAGOSTEA DIN TEI
44_Dreamer.ogg = Dreamer (Radio Edit)
45_F_CK.ogg = F_CK
46_Put_Your_Hands.ogg = Put Your Hands Up
47_FIGHT_FOR_YOUR_RIGHT.ogg = FIGHT FOR YOUR RIGHT
48_Fun_Loving_Spirit.ogg = Fun Loving Spirit
49_Give_Up_or_Keep_Trying.ogg = Give Up or Keep Trying
50_Guile_Aggressive_Remix.ogg = Guile (Aggressive Remix)
51_HOW_U_LIKE_BASS.ogg = HOW U LIKE BASS
52_I_Luv_U_Baby.ogg = I Luv U Baby
53_I_Touch_Myself.ogg = I Touch Myself
54_This_is_My_Destiny.ogg = This is My Destiny
55_The_Creeps.ogg = The Creeps (Youre Giving Me)
56_Infected_Delaction_Remix.ogg = Infected (Delaction Remix)
57_Kibun_Joujou.ogg = Kibun Joujou
58_Tell_It_To_My_Heart.ogg = Tell It To My Heart
59_Lets_Go_Away.ogg = Lets Go Away
60_Like_a_Butterfly.ogg = Like a Butterfly
61_Linda_Linda.ogg = Linda Linda
62_LOVESHINE.ogg = LOVESHINE
63_Marry_You.ogg = Marry You
64_Maximum_Acceleration.ogg = Maximum Acceleration
65_Mode_Select_Maxi5.ogg = Mode Select Maxi5
66_Techno_Syndrome_Mortal_Kombat.ogg = Techno Syndrome (Mortal Kombat)
67_MAIN_THEME.ogg = MAIN THEME
68_Never_Too_Much.ogg = Never Too Much
69_F1_Theme.ogg = The Chain - F1 Theme
70_Waterfall.ogg = Waterfall
71_Out_of_Touch.ogg = Out of Touch
72_Pride_Theme_KILLFAC3_Remix.ogg = Pride Theme (KILLFAC3 Remix)
73_Rotterdom_Nation_Foo_Mix.ogg = Rotterdom Nation (Foo Mix)
74_Santa_Maria_Trance_Mix.ogg = Santa Maria (Trance Mix)
75_What_You_Want_What_You_Need.ogg = What You Want What You Need
76_Shape_of_You.ogg = Shape of You
77_Simon_Says.ogg = Simon Says
78_Sing.ogg = Sing
79_Sky_High.ogg = Sky High
80_Youre_The_Best.ogg = Youre The Best
81_Soulgrabbe.ogg = Soulgrabbe
82_STORM.ogg = STORM
83_velfarre_2000.ogg = velfarre 2000
84_The_Touch.ogg = The Touch
85_Theme_from_S_Express.ogg = Theme from S-Express
86_Borderline.ogg = Borderline
87_Dont_You_Forget_About_Me.ogg = Dont You Forget About Me
88_EUROBEAT.ogg = EUROBEAT
89_How_You_Remind_Me.ogg = How You Remind Me
90_Livin_On_A_Prayer.ogg = Livin On A Prayer
91_F_Zero.ogg = F Zero
92_Formula_1_Theme_by_Brian_Tyler.ogg = Formula 1 Theme by Brian Tyler
93_910214.ogg = 910214
94_Beautiful_Original_Mix.ogg = Beautiful (Original Mix)
95_DANCE_AVEC_MOI_Airscape_Remix.ogg = DANCE AVEC MOI (Airscape Remix)
96_De_Janeiro.ogg = De Janeiro
97_Dhalsim_TEKINA_Remix.ogg = Dhalsim (TEKINA Remix)
98_Dream_Snatcher.ogg = Dream Snatcher
99_Everynight_Everyday.ogg = Everynight Everyday
100_Fruity_Fruity.ogg = Fruity Fruity
101_FUTURE_DRIVEN.ogg = FUTURE DRIVEN
102_Get_Ready_for_This.ogg = Get Ready for This
103_Ghosts_Vincent_De_Moor_Original.ogg = Ghosts (Vincent De Moor Original)
104_Heaven.ogg = Heaven
105_Jump_Around.ogg = Jump Around
106_Livin_La_Vida_Loca.ogg = Livin La Vida Loca
107_MADE_OF_FIRE.ogg = MADE OF FIRE
108_Maximum_Overdrive.ogg = Maximum Overdrive (KC Radio Mix)
109_Moon_Over_The_Castle.ogg = Moon Over The Castle (GTs Theme)
110_Move_And_Proceed.ogg = Move And Proceed
111_My_Heart_Will_Go_On.ogg = My Heart Will Go On (KCP Remix)
112_NIGHT_OF_FIRE.ogg = NIGHT OF FIRE
113_Nitro_Mantra.ogg = Nitro Mantra
114_NITRO_RIGHT_NOW.ogg = NITRO RIGHT NOW (from RIDGE RACER)
115_On_The_Move.ogg = On The Move (DuMonde Remix)
116_Pump_Up_The_Volume.ogg = Pump Up The Volume
117_Rave_4_U_dancing.ogg = Rave 4 U dancing
118_Sandstorm.ogg = Sandstorm (Original Mix)
119_Seal_Clubbing.ogg = Seal Clubbing
120_Set_You_Free.ogg = Set You Free
121_Shake.ogg = Shake
122_Sick.ogg = Sick Robbie Rivera Louie Padilla
123_Smack_My_Bitch_Up.ogg = Smack My Bitch Up (Sub Focus Remix)
124_SPENTE_LE_STELLE.ogg = SPENTE LE STELLE (Yomanda Dub)
125_Stage_2.ogg = Stage 2
126_Sweet_Child_Of_Mine.ogg = Sweet Child Of Mine
127_Tek_Trek.ogg = Tek Trek
128_THE_TIME_IS_NOW.ogg = THE TIME IS NOW
129_Twilight_Zone.ogg = Twilight-Zone
130_U_Sure_Do.ogg = U Sure Do
131_Voodoo_People.ogg = Voodoo People Pendulum Remix
132_What_s_New_Pussy_Cat.ogg = Whats New Pussy Cat
133_Like_A_Virgin.ogg = Like A Virgin
134_Papa_Dont_Preach.ogg = Papa Dont Preach
135_No_Limit.ogg = No Limit
136_Lets_Go_Away_karaoke.ogg = Lets Go Away (karaoke)
137_Nightmare.ogg = Nightmare (Sinister Strings Edit)
138_Mario_Circuit.ogg = Mario Circuit
139_Freed_From_Desire.ogg = Freed From Desire
140_Hey_Baby.ogg = Hey Baby
141_Bryan_Adams_Run_To_You = Run To You
Last_Wave.ogg = Last Wave
SEGA441.ogg = SEGA Intro
Beach_wave.ogg = Beach Waves
title_pattern1.ogg = C2C Title 1
title_01.ogg = C2C Opening Jingle
or2ed1.ogg = Ending 1
or2ed2.ogg = Ending 2
or2ed3a.ogg = Ending 3a
or2ed3b.ogg = Ending 3b
or2ed4.ogg = Ending 4
or2ed5.ogg = Ending 5

**Comment by emoose** [comment]
Ahh I thought you had tracks between 141 and Last_Wave.ogg, probably not a comment thing then.

Did notice the 141_Bryan_Adams_Run_To_You track is missing .ogg extension, could be stopping CDSwitcher from seeing it.

**Comment by lance8765** [comment]
If the extension doesn't appear you get Splash Wave. It happened to me when CDSwitcher was just implemented (see here: https://github.com/emoose/OutRun2006Tweaks/issues/9#issuecomment-2186445451)

**Comment by areyabuzzin** [comment]
> Ahh I thought you had tracks between 141 and Last_Wave.ogg, probably not a comment thing then.
> 
> Did notice the 141_Bryan_Adams_Run_To_You track is missing .ogg extension, could be stopping CDSwitcher from seeing it.

I put it back in and it's still the same, reverts back to Splash Wave track.

**Comment by areyabuzzin** [comment]
STOP THE 🕰 
I got it working now! 
It was the missing .ogg (I forgot to put the track back in the sound folder!) 👍

**Comment by Tenome** [comment]
The CD switcher is really sensitive, you have to double check it when you add songs, I had a track that I forgot to remove from the INI and it made the game crash lol.
