### ISSUE TITLE
[Bug]: ASUS Rog Ally X - Crash on startup

### ISSUE THREAD

**Issue by namcojr** [emoose/OutRun2006Tweaks#87]
### Tweaks version

0.4.2

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

When running on an ROG Ally X using a Z1 Extreme APU (mostly like a 7840U), with the default configuration and the original game set to 1920x1080, the game will enter full screen for 2-3 seconds and then simply exit without any errors shown in the log. I have tried several settings to try and see whether i could get any different reaction from the game, but nothing changes the behaviour.

I also have a GPD Win4 handheld with an 8840U APU and the game launches perfectly with no issues.

[OutRun2006Tweaks.log](https://github.com/user-attachments/files/16357758/OutRun2006Tweaks.log)

**Comment by namcojr** [comment]
As additional information i can add that the regular game runs normally. The AMD drivers differ from the GPD Win4 and ASUS ROG AllyX, the AllyX having an older version specifically designed for it (may this be the cause?).

**Comment by emoose** [comment]
Hm, if the regular game runs then some change must be breaking it, pretty much all the changes can be disabled with the INI, could you see if this INI lets it run?

[OutRun2006Tweaks.ini.txt](https://github.com/user-attachments/files/16363845/OutRun2006Tweaks.ini.txt)
(remove .txt extension, github doesn't like .ini some reason)

Everything should be disabled there, if that works you could try copying sections over from the default INI https://github.com/emoose/OutRun2006Tweaks/blob/master/OutRun2006Tweaks.ini and see which section stops it from working, then hopefully we can narrow down which is breaking it

**Comment by namcojr** [comment]
Thank you very much for your reply. Indeed it does work like this. I will do as you asked, i just need some time and will get back to you as soon as i figure out which one is breaking it.

**Comment by namcojr** [comment]
So, here's the culprit:
# Allows game to detect newly plugged in devices, rather than needing a restart
ControllerHotPlug = true

By setting that to true, at least on my AllyX makes the game crash on startup after some 2-3 seconds as described.
Also, this setting:

FramerateFastLoad = 3

Makes the SEGA logo appear somewhat faint on startup, having it set to 1 fixes this, but the game does take a while longer to load. I can live with 3 :)

Hope this helps more people, cheers!
