### ISSUE TITLE
Rush a Difficulty 1989 on the PC version

### ISSUE THREAD

**Issue by lance8765** [emoose/OutRun2006Tweaks#9]
Ok, we've already discussed about this in Issue #4, but i'll repeat it here since it was a little "off-topic". I'm reposting it separately just for convenience.

Like i already said, the original version of "Rush A Difficulty" music from Turbo OutRun doesn't start from the very beginning, it's missing the first few seconds. It is noticeable even when the music restarts from the beginning on long races. This issue doesn't happen on ALL console versions, on the arcade versions, or in officially released official soundtracks.

The audio file is named 14_Rush_a_Difficulty_1989.ogg, while "SEL_14_Rush_a_Difficulty.ogg" (which is used in music selection screens) is totally fine, as you said.

So yeah, the problem here is to find if there's a way to make the song "complete" without having to actually replace the .OGG file (which is totally doable, but possibly illegal if included in your release?)

**Comment by emoose** [comment]
Don't really know that much about audio things but guess it could probably be spliced together from the two files, I know ffmpeg can be used to splice video so guess that would probably work for audio too, seems to be able to read/write .oggs at least.

Not really sure what the best way is to figure out the correct times it needs to copy the splice over, but if we did have the timings we could probably include some .bat script to merge them into a full track automatically (had a look in audacity but I was in over my head there... the waveforms seemed a bit different between the two as well, so could be some quality difference in them)

Besides that I was able to re-encode the .adx file from arcade over to ogg, game seems to play it back fine.
`ffmpeg -i 05rush_a_difficulty_cvt.adx -qscale:a 4 output.ogg` makes a ogg with similar bitrate & filesize to original, qscale can be increased for higher bitrate.

One thought is maybe making a delta patch between this arcade-reencode and the C2C version, and only include that delta patch + tools to apply it to original, the patch itself would be useless on its own without having the original C2C ogg, so maybe would make it a bit more legit to include.

I think adx is already lossy-compressed though, so maybe would be better to create an ogg from some .flac version instead.

**Comment by emoose** [comment]
Took a bit of digging but was able to find uncompressed version of the same Rush a Difficulty used in C2C, most soundtrack CDs seemed to use a different flatter version for some reason.

Encoded it to ogg and made an xdelta patch for it, made a batch file to handle applying it too.
If you extract this zip into C2C root folder and run SoundtrackFix.bat it should be able to update it all automatically:

[Outrun2006-SoundtrackFix-1.0.zip](https://github.com/user-attachments/files/15909779/Outrun2006-SoundtrackFix-1.0.zip)

Hopefully can include this in the next release maybe, if anyone has any issues let me know.

**Comment by lance8765** [comment]
Yeah... seems fine to me. At last. Thank you again.

ps: do you think it'll ever be possible to implement the four extra tracks exclusive to the Japanese PS2 version, without having to replace the existing ones?

**Comment by DonelBueno** [comment]
> Took a bit of digging but was able to find uncompressed version of the same Rush a Difficulty used in C2C, most soundtrack CDs seemed to use a different flatter version for some reason.
> 
> Encoded it to ogg and made an xdelta patch for it, made a batch file to handle applying it too. If you extract this zip into C2C root folder and run SoundtrackFix.bat it should be able to update it all automatically:
> 
> [Outrun2006-SoundtrackFix-1.0.zip](https://github.com/user-attachments/files/15909779/Outrun2006-SoundtrackFix-1.0.zip)
> 
> Hopefully can include this in the next release, if anyone has any issues let me know.

Is it possible to make the game load higher bitrate .ogg? That would be a nice bonus, higher quality OST.

**Comment by emoose** [comment]
>Is it possible to make the game load higher bitrate .ogg? That would be a nice bonus, higher quality OST.
I think it can load pretty much any bitrate as long as it's in ogg format (there might be some support for uncompressed WAV files as well but think that might need a code patch to use it)

Tracking down good uncompressed versions might take a little work though, seems they released lots of different variants of most songs :/

>ps: do you think it'll ever be possible to implement the four extra tracks exclusive to the Japanese PS2 version, without having to replace the existing ones?

Might be able to force them to play during a race, not really sure about adding actual options to the music selector though.

Had a look into switching music during gameplay a little while ago, seems games music loader pretty much just takes in a ogg filename and starts playing it, so should be possible to make it load from our own paths instead.

(their music code is very basic really, seems it's based on some [windows sample code](https://github.com/svn2github/tokamak/blob/3a43e7c8afa6686ff68ed3a6e11b701067d3f7f8/d3dapp/dxut/DXUTsound.cpp#L44) for using directsound, probably why it didn't have working loop points as well...)

**Comment by lance8765** [comment]
Just saw commit #38... seriously? You're crazy, and i love it XD

**Comment by emoose** [comment]
Here's a build with the CDSwitcher stuff, use Q/E or Back/RS+Back to switch tracks during race, you can also add your own tracks at the end of the INI too (or remove tracks that you don't want / reorder them):

[OutRun2006Tweaks-0.3.0-rc1.zip](https://github.com/user-attachments/files/15935677/OutRun2006Tweaks-0.3.0-rc1.zip)

Uncompressed wav should also work if you have it named the same as the OGG (you can use uncompressed ones without needing the CDSwitcher stuff enabled) - looks like the Outrun 20th anniversary CDs have most of the C2C music, except the Turbo Outrun 1989 tracks sound a bit different there.

**Comment by lance8765** [comment]
Oh, great. I was going to ask if the CDSwitcher has specific "rules" like not playing the "SEL_" or the ""or2ed#" tracks, but i guess it's not necessary for now. :D

**Comment by lance8765** [comment]
Uhm, i'm currently unable to test versions v0.3.0... i'm getting the following error: "The procedure entry point SetThreadDescription could not be located in the dynamic link library KERNEL32.dll", version v0.2.5 was working fine.

**Comment by lance8765** [comment]
> hm, i'm currently unable to test versions v0.3.0... i'm getting the following error: "The procedure entry point SetThreadDescription could not be located in the dynamic link library KERNEL32.dll", version v0.2.5 was working fine.

Uhm, i'm currently unable to test versions v0.3.0... i'm getting the following error: "The procedure entry point SetThreadDescription could not be located in the dynamic link library KERNEL32.dll", version v0.2.5 was working fine.

**Comment by emoose** [comment]
Ah darn seems that's some debug code I left in, didn't realize it wasn't included in win7, thanks for letting me know.

https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.3.0-3 should hopefully have it fixed

**Comment by lance8765** [comment]
Much obliged. It works again. Also the CDSwitcher is really cool. Reminds me of OutRunners.

However, i tried to add some custom tracks, but all i get is Splash Wave (the very first track, aka 01_Splash_wave.ogg), and yes the tracks were in OGG format.

**Comment by lance8765** [comment]
Ok, i'm an idiot. The custom tracks work, i just forgot to put the file format at the end of the name lol.

However, some characters aren't displayed properly. One of my tracks was named "Passing Breeze [H.] Arrange Ver.
" (yeah, i have tried adding those bonus tracks from the Japanese PS2 version) but instead of the [ ], it was named xH.♡︎ (yeah, it's supposed to be a small heart, and it was RED in-game lol)

**Comment by emoose** [comment]
>but instead of the [ ], it was named xH.♡︎ (and yeah, that's a small heart, and it's even RED in-game lol)

Ah looks like the font didn't include square brackets for some reason, some other fonts do include them though, probably worth adding an option to let you change it, will add something for it in 0.3.

**Comment by lance8765** [comment]
> > but instead of the [ ], it was named xH.♡︎ (and yeah, that's a small heart, and it's even RED in-game lol)
> 
> Ah looks like the font didn't include square brackets for some reason, some other fonts do include them though, probably worth adding an option to let you change it, will add something for it in 0.3.

Thank you again. Will probably test it tomorrow. Also did you read that part about the "unused" audio files in the other post above?

**Comment by lance8765** [comment]
I've just discovered that the fix for Rush a Difficulty is now mentioned in the PCGamingWiki page. Congratulations and thanks again! Finally it got the attention it deserved, after 18+ years.
