### ISSUE TITLE
[Bug]: TextureDump doesn't seem to work on player car textures.

### ISSUE THREAD

**Issue by Tenome** [emoose/OutRun2006Tweaks#95]
### Tweaks version

Commit 4a97d98

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

I tried dumping the textures of the 512 BB (OR) which seem to be contained in obj_rc_512bb_t_pmt (rival car instead of the expected obj_plcar). However, when I check the dumped texture folder, it seems to dump everything except the main texture. The texture that's dumped (9C126A6C_256x256.dds) in the folder seems to be for rivals/time trial ghosts (note the different number, 88 instead of 66). I tried editing the texture anyway (maybe it just swaps the number), but it didn't affect the car's texture. Is the texture contained within the 3D model archive instead? It does dump the other miscellaneous textures such as the license plate, headlights, etc.

![image](https://github.com/user-attachments/assets/93221484-45ec-4e0d-bc69-67ca922bc62c)
![resized9C126A6C_256x256](https://github.com/user-attachments/assets/b7571604-9ab2-4645-954b-428d35abf664)

**Comment by emoose** [comment]
Were you able to find anything for this? There is one other texture loading func which tweaks doesn't hook into atm, it's to do with cube textures though which I thought were only to do with cubemaps/skybox, but guess car textures might be using that too, could try looking into hooking that as well.

**Comment by Tenome** [comment]
I tried it again with Ninja Ripper just now, and the decals on the livery dumped by themselves as separate textures (which I think it did for Tweaks' dump as well). Maybe the player car color isn't a a texture at all, but just a color value which then gets the textures pasted onto it? I didn't see a standalone texture like with rival/ghost cars.

**Comment by Tenome** [comment]
I think I found the folder that hosts the color sprites. obj_pc_color_pmt contains 8x8 color squares that are probably tiled over the entire car. Unfortunately this probably means you can't put anything other than basic color swaps over the player car.

**Comment by lance8765** [comment]
I'm still patiently hoping to see that "Xbox blue" i mentioned in this issue ahah: https://github.com/emoose/OutRun2006Tweaks/issues/20#issuecomment-2194918117

**Comment by Tenome** [comment]
It looks like he dumped the color sprites from the Xbox version, why not just add it yourself as a custom texture? It probably won't be added officially.

**Comment by lance8765** [comment]
Oh, this must be a joke... Capcom Fighting Collection 2, Castlevania Dominus Collection, and now THIS, on the same day. Am i dreaming? :O
